### ISSUE TITLE
I can't use non-cascade elements in cascade elements

### ISSUE THREAD

**Issue by Nekmo** [jrief/djangocms-cascade#100]
I want to include elements that are not in cascade (for example, text) and I do not get it. Is this normal?

![out 04d](https://cloud.githubusercontent.com/assets/740106/9687963/a4728d4a-532c-11e5-8192-fd42c269e39d.gif)

**Comment by jrief** [comment]
Could you please specify which ones?
Also, please have a look at the ALIEN_PLUGINS settings.
If a plugin needs to restrict its width according to the grid, then its
probably easier to add a new plugin to the "Cascade" ecosystem.
Am 04.09.2015 17:44 schrieb "Nekmo" <notifications@github.com>:

**Comment by jrief** [comment]
Now I can see the embedded video.
Please use the internal Link plugin from Cascade, rather than the djangocms-link plugin.

**Comment by rfleschenberg** [comment]
@Nekmo, I hope this solves your problem? If there still is an issue, please open a new issue on Github. Thanks!
