### ISSUE TITLE
UnboundLocalError when copy&pasting column with image.

### ISSUE THREAD

**Issue by linevich** [jrief/djangocms-cascade#101]
I've got the next error when trying to copy&paste row>column>image:
```
UnboundLocalError at /uk/exposition/  local variable 'width' referenced before assignment
```
[Traceback here.](http://paste.ofcode.org/fdc7z4BuhgeJJpsvezpUxR)

**Comment by jrief** [comment]
Please recheck. This is a really stupid bug.

**Comment by linevich** [comment]
Not working, the same error.

**Comment by jrief** [comment]
Did you use the latest commit 9e7458b418ffe9efbde99c35b9b7361422752400 from GitHub?
What's your ``container_max_widths`` in your ``CMS_PLACEHOLDER_CONF`` settings for that specific placeholder?

**Comment by linevich** [comment]
Sorry, It was my mistake, now all working, thank you :)

**Comment by linevich** [comment]
This error still occurs in 0.6.1, can you fix it?
