### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by jtiki** [jrief/djangocms-cascade#106]
The documentation implies that the bootstrap3_tags are still in this project (http://djangocms-cascade.readthedocs.org/en/latest/bootstrap3/navbar.html), but this tag has seemingly been moved into its own package (https://github.com/jrief/djangocms-bootstrap3).

**Comment by jrief** [comment]
Sorry and thanks for reporting.
A PR fixing this documentation bus is welcomed.

**Comment by jtiki** [comment]
This issue was addressed in [Merge 108](https://github.com/jrief/djangocms-cascade/pull/108)
