### ISSUE TITLE
Maintainer notice: Drop support for Django-1.6 ?

### ISSUE THREAD

**Issue by jrief** [jrief/djangocms-cascade#109]
**As of 2015-Oct-07, the code-base has been refactored to support Django-1.9. If somebody uses
DjangoCMS-Cascade with Django-1.6 or lower, please reply here. Otherwise I'll drop support
for deprecated Django versions.**

**Comment by schacki** [comment]
Is django-1.6 already deprecated? I think 1.6 is still supported.
Is the djangocms-cascade version that supports django-1.9 not compatible with django-1.6 or is it just the demo-project that is not?

**Comment by rfleschenberg** [comment]
I think we can close this issue now. We currently support Django 1.8. Django 1.9 is not yet supported, but hopefully in the next release.
