### ISSUE TITLE
Option "disabled" not working for color and background params.

### ISSUE THREAD

**Issue by linevich** [jrief/djangocms-cascade#110]
I changed custom styles settings for `BootstrapContainerPlugin`. 
Now when I add new container it has white font color and background, option `disabled` for color and background doesn't change anything.
Previously I having the same issue - https://github.com/jrief/djangocms-cascade/issues/93, but it strangely disappeared and come back again after reloading server.

**Comment by rfleschenberg** [comment]
@linevich, can you please try to reproduce this with the current release?

**Comment by haricot** [comment]
It's resolved in version 0.15.3 8c7117d20f971a3d13a3a63f0f6332b70e9fbbea

**Comment by linevich** [comment]
Sorry guys I no longer working with DjangoCMS and cascade. If @haricot says that it was fixed I guess we can close the issue.

**Comment by jrief** [comment]
@linevich what a petty! Which CMS are you using now?

**Comment by linevich** [comment]
None. I'm working on a big Django project as a backend developer. :)
