### ISSUE TITLE
Problem during a copy of a Row plugin

### ISSUE THREAD

**Issue by adrien-delhorme** [jrief/djangocms-cascade#113]
When I try to copy a Row plugin (that contains columns), and then paste it in another Container plugin, I do not get any error, but the Row plugin displays "Row with 0 columns".

![capture d ecran 2015-10-30 a 09 53 36](https://cloud.githubusercontent.com/assets/1597706/10841725/2189cbbe-7eec-11e5-9560-4b1afb3f6324.png)

If there are Image plugins in the columns, I get an AssertionError in `cmsplugin_cascade/bootstrap3/utils.py in get_image_tags, line 82` because `options['container_max_widths']` is empty.

**Comment by jrief** [comment]
Thanks for reporting, I'll have a look as soon as I have some time to.
About the first issue, I assume its counts correctly after you refresh the page. I believe this is because the RowPlugin is not informed whenever some children are appended.

The second issue should not happen.

Just a question, do you paste on the same CMS page, or on a different one?

**Comment by adrien-delhorme** [comment]
Even after a page refresh, the "Row with 0 columns" is still there, and the behavior is the same if I paste on the same page or on another one.

**Comment by rfleschenberg** [comment]
@adrien-delhorme, do you still experience this issue with the current release?

**Comment by adrien-delhorme** [comment]
Yes, still the same error.

**Comment by frnhr** [comment]
Happened to me too, a few months ago (so no details, sorry).

**Comment by jrief** [comment]
@frnhr @adrien-delhorme I had a look at this problem and it is related to a caching issue in django-cms. I haven't found any workaround to solve this yet. Please have a look at the table column ``cms_cmsplugin.num_childs``. In django-cms, I could not find any method to enforce updating it.

**Comment by rfleschenberg** [comment]
Should we file an issue against django-cms?

**Comment by haricot** [comment]
This problem no longer exists. it works, i tested with django-cms 3.4.5 and 3.5.1 and python3.
I think this issue can be closed.

**Comment by jrief** [comment]
@haricot thanks for testing!
