### ISSUE TITLE
settings breakpoints not affecting the container

### ISSUE THREAD

**Issue by davidetruffo** [jrief/djangocms-cascade#131]
Awesomeness as usual :)

One minor thing i've found is this:
I can override the boostrap's breakpoints and mediaquery from my settings, but then i bumped into the following portions that are not based on the settings:

in bootstrap3/container.py
line 44
``````
WIDGET_CHOICES = (
        ('xs', _("Tiny (<{sm[0]}px)".format(**BS3_BREAKPOINTS))),
        ('sm', _("Small (≥{sm[0]}px and <{md[0]}px)".format(**BS3_BREAKPOINTS))),
        ('md', _("Medium (≥{md[0]}px and <{lg[0]}px)".format(**BS3_BREAKPOINTS))),
        ('lg', _("Large (≥{lg[0]}px and <{xl[0]}px)".format(**BS3_BREAKPOINTS))),
        ('xl', _("XLarge (≥{xl[0]}px)".format(**BS3_BREAKPOINTS))), # added this to show my custom breaking point
)
```````

line 55 (or a bit above):
``````
    glossary_fields = (
        PartialFormField('breakpoints',
            widgets.CheckboxSelectMultiple(choices=WIDGET_CHOICES, renderer=ContainerBreakpointsRenderer),
            label=_('Available Breakpoints'),
            initial=['xl', 'lg', 'md', 'sm', 'xs'], #changed this to match the default selection
            help_text=_("Supported display widths for Bootstrap's grid system.")
        ),
``````

Would it be hard to implement? it would be fantastic because bootstrap4 actually lets the user set whichever breakpoint he/she desires :)

**Comment by jrief** [comment]
Thanks for reporting.
If I get you right here, this is only while editing the **BootstrapContainerPlugin**, so its only that I display the wrong numbers?

If its this, then it should be quite easy to fix.

**Comment by davidetruffo** [comment]
Yes, it only happens for the **BootstrapContainerPlugin**, and the numbers are ok :)
My question was more about the WIDGET_CHOICES, because as far as i can tell, it is hardcoded, and it doesn't get the settings (not the default nor the custom ones)

In the specific case:
my_project/settings.py
``````
CMSPLUGIN_CASCADE = {
    ...
    'bootstrap3': {
        'breakpoints': (
            ('xs', (768, 'mobile-phone', _("mobile phones"), 750)),
            ('sm', (768, 'tablet', _("tablets"), 750)),
            ('md', (992, 'laptop', _("laptops"), 970)),
            ('lg', (1200, 'desktop', _("large desktops"), 1170)),
            ('xl', (1600, 'desktop icon-large', _("xlarge desktops"), 1570)),
        ),
    }
}
``````
But in bootstrap3/container.py, the choices are hardcoded, and they look like this (pleas note that there is no **"xl"** breakpoint):
``````
WIDGET_CHOICES = (
        ('xs', _("Tiny (<{sm[0]}px)".format(**BS3_BREAKPOINTS))),
        ('sm', _("Small (≥{sm[0]}px and <{md[0]}px)".format(**BS3_BREAKPOINTS))),
        ('md', _("Medium (≥{md[0]}px and <{lg[0]}px)".format(**BS3_BREAKPOINTS))),
        ('lg', _("Large (≥{lg[0]}px)".format(**BS3_BREAKPOINTS))),
)
``````
maybe this list could be built dynamically using the settings?
(i'm not sure if i'd understand myself, so if i'm not clear yet please insist :) )

**Comment by jrief** [comment]
Sorry for not getting back earlier.
AFAIK, the breakpoint ``xl`` is not part of the Bootstrap library, so chances are small that I will add non-standards to this library.

If you want to make WIDGET_CHOICES configurable using a pattern similar to those used in bootstrap3/settings.py, please go ahead and create a pull request. I then might merge it.

**Comment by davidetruffo** [comment]
Hi @jrief 
you are right, the `xl` breakpoint is not a default but looking forward, bootstrap made it quite easy to add custom breakpoints with custom names in bootstrap4, that's why it would be nice to have such a feature.

I've started working on it, and i'll come up with a pull request asap :)

**Comment by jrief** [comment]
had no time yet to work with BS4 but from its white papers it seems promising.
Please put everything into a new folder named ``bootstrap4``.

**Comment by davidetruffo** [comment]
I had a chance to work with BS4, and it is actually very promising!
The markup is not different, and the changes i've made would work with bootstrap3 as well, should i make a `bootstrap4` folder anyway even if it would be a copy of `bootstrap3`? just asking :)

**Comment by jrief** [comment]
Hmm, in that case no since we want to stay DRY.
Then unfortunately bootstrap3 was the wrong choice for naming that folder. Anyway keep it and then we'll see.

**Comment by rfleschenberg** [comment]
IIUC, PR #137 has fixed this issue.
