### ISSUE TITLE
Carousel Slide plugin different form

### ISSUE THREAD

**Issue by davidetruffo** [jrief/djangocms-cascade#132]
Hello!
I'm sorry to bother you again, but I think i've bumped into another bug.
If I add a carousel plugin, I can choose how many slides i want, then each slide-plugin has an image field and a text field. This all works smoothly.

When i try to add a slide to an existing carousel, the slide plugin get's added, but i only get an image field (ImageForm), and even if i try to save that image in the slide, i get a 500 error because:

**image.py, line: 31**
assert fails
`````
    def clean_glossary(self):
        assert isinstance(self.cleaned_data['glossary'], dict)
        return self.cleaned_data['glossary']
`````

and **carousel.py, line: 135**
obj is None
`````
def get_form(self, request, obj=None, **kwargs):
        if obj:
            caption = self.html_parser.unescape(obj.glossary.get('caption', ''))
            obj.glossary.update(caption=caption)
            # define glossary fields on the fly, because the TextEditorWidget requires the plugin_pk
            text_editor_widget = TextEditorWidget(installed_plugins=[TextLinkPlugin], pk=obj.pk,
                                           placeholder=obj.placeholder, plugin_language=obj.language)
            kwargs['glossary_fields'] = (
                PartialFormField('caption', text_editor_widget, label=_("Slide Caption"),
                    help_text=_("Caption text to be laid over the backgroud image."),
                ),
            )
        return super(CarouselSlidePlugin, self).get_form(request, obj, **kwargs)
`````

**Comment by jrief** [comment]
your line numbers don't fit with my version.
Could you please upgrade to the latest version from Github and paste a stacktrace.

**Comment by davidetruffo** [comment]
I'm on 0.7.1 (the latest release)
Here are the lines i meant, linked in the github repo.
https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/image.py#L31

https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/carousel.py#L134

**Comment by davidetruffo** [comment]
Hi! Do you have any news on that?

**Comment by jrief** [comment]
sorry, no time yet

but feel free to remind me :)

**Comment by davidetruffo** [comment]
as stated above: 
if i create a carousel plugin, i select how many slides it needs to have, and all goes smoothly. Slides get added using the picture form, and it is possible to add a caption as well.
If i **add a slide to an existing carousel**, this shows up as a regular image form (with no caption), and it also gives an error on save.

I'm looking into it now, trying to figure out what's going on, if i find something i'll make a pull request.
Meanwhile, if you have any hints, they would be more than welcome! :)

**Comment by shaunbrady** [comment]
I believe we are running across this same issue.

**Comment by jrief** [comment]
@davidetruffo could you please retest with the current version from GitHub and retest in your environment. If everything works give me feedback, so that I can release 0.7.3.

sorry, that this all took so long. I was too busy on other projects.

**Comment by jrief** [comment]
@davidetruffo ping

**Comment by davidetruffo** [comment]
sorry @jrief , haven't had time yet. I'll try tomorrow!

**Comment by davidetruffo** [comment]
@jrief it worked like a charm! :+1:
