### ISSUE TITLE
BootstrapPanelPlugin does not support custom CSS classes 

### ISSUE THREAD

**Issue by jtiki** [jrief/djangocms-cascade#133]
I was working with panels today and noticed that you can add custom classes to panels, but they do not render with the classes. I wrote a quick fix for my project, but could easily fork the repo and add it as a permanent fix.

**Comment by jrief** [comment]
Just had a look at the templates, and yes you can't add customized classes.
Could you please try to change line 2 in file ``templates/bootstrap3/panel.html`` to

```
<div class="panel {{ panel_type }} {{ instance.css_classes }}">
```

and tell me, if this fixes your problem. I then will add it to the next release.

**Comment by jrief** [comment]
@jtiki Since you did not answer, I now closed this issue.
