### ISSUE TITLE
Unable to add Button to SimpleWrapper

### ISSUE THREAD

**Issue by emve-dev** [jrief/djangocms-cascade#134]
I was wondering if this is limitation necessary?
For example if I add a Column in a Row and a SimpleWrapper <div> (that could contain some Text) inside that Column it'll be a good idea to be able to add a Button in that wrapper. 
It is a common markup solution to make bootstrap themes using nested div's with css classes, that is why I'm having a hard time implementing themes that I've bought using cascade plugin.
I'm not claiming but reaching out for help.
Haven't found any solution in docs or source code.
Can anyone suggest a workaround?

**Comment by jrief** [comment]
Ups, indeed that would be useful. Please add it to the list of allowed
parents.
Am 12.02.2016 00:55 schrieb "emve-dev" <notifications@github.com>:

**Comment by jrief** [comment]
sorry, that this all took so long. I was too busy on other projects.
