### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by asmaps** [jrief/djangocms-cascade#14]
I'd like to contribute german translations to the project, but I can't find any doc on how to translate things. Is there a transifex project for this? If not, would it be possible to create one?

**Comment by jrief** [comment]
The only language besides English is Ukrainian. Many new lemmas have to be translated into German. Please send me an invitation for Transiflex.

**Comment by asmaps** [comment]
Actually you're already the owner and maintainer... you should be able to manage everything? http://i.imgur.com/6Fz2cv5.png

**Comment by rfleschenberg** [comment]
Is this issue still something we need to look at? What's the current state on this?

**Comment by rfleschenberg** [comment]
Closing this. If anyone wants to work on translations and needs assistance, please file a new issue or contact me directly. Thanks!
