### ISSUE TITLE
Only developers know how to "hold ctrl or cmd on a mac" :)

### ISSUE THREAD

**Issue by frnhr** [jrief/djangocms-cascade#154]
For multiple custom CSS classes, we should probably change this:

![screen shot 2016-03-24 at 16 13 44](https://cloud.githubusercontent.com/assets/1173748/14021684/ddfb84c8-f1dc-11e5-8d3d-8e4f354cd3cf.png)

to this:

![screen shot 2016-03-24 at 16 15 58](https://cloud.githubusercontent.com/assets/1173748/14021687/e3757b7a-f1dc-11e5-85f3-a1c06af8a7f6.png)

All it takes is change `extra_fields/mixins.py` from:

    widget = widgets.SelectMultiple(choices=choices)

to:

    widget = widgets.CheckboxSelectMultiple(choices=choices)

Am I missing some reasons not to make the change?

**Comment by rfleschenberg** [comment]
Sounds good to me. Want to prepare a pull request?

**Comment by frnhr** [comment]
sure, here it is: https://github.com/jrief/djangocms-cascade/pull/155

**Comment by frnhr** [comment]
The PR has been merged, so closing this issue.
