### ISSUE TITLE
Container can't be added anywhere

### ISSUE THREAD

**Issue by emve-dev** [jrief/djangocms-cascade#162]
Hello, 
Recently I updated to the latest version 0.8.2 and no longer can add BootstrapContainer to SimpleWrapper. My markup is designed that way that I split logical elements into `section` html tag and inside section I create a container and a row with columns. So on version 0.7.1 I added `section` with simple wrapper plugin and inside the section added containers with BootstrapContainerPlugin. I cannot do it anymore. I guess the reason is this commit 2c8fd6f. 
My question is why you decided to make this change?

**Comment by jrief** [comment]
Sorry for the inconvenience. This has already been fixed by ed9c21fef1122515843f23ef2be00df7a8652ec1. It would have been an error to allow BS-Containers as children of anything. Now the SimpleWrapperPlugin acts "transparently", which means that you can add anything.

**Comment by emve-dev** [comment]
Now I see why you did it. Thank you for response.  Your plugin is very helpful, hope it merges into django-cms core someday 👍

**Comment by jrief** [comment]
> Your plugin is very helpful, hope it merges into django-cms core someday

Thanks for emphasizing this. If you have any idea for an additional and reusable plugin, please let me know.
