### ISSUE TITLE
Test with djangoCMS version 3.3.0

### ISSUE THREAD

**Issue by jrief** [jrief/djangocms-cascade#168]
Currently Cascade fails two test-cases, when tested against djangoCMS version 3.3.0. They both are part of ``test_http.py``.
In branch **sections**, all problematic methods have been adopted to run with djangoCMS version 3.3.0.
@rfleschenberg please add djangoCMS version 3.3.0 to the test matrix and check for that remaining test.

**Comment by rfleschenberg** [comment]
@jrief: tox already tests against djangoCMS 3.3, we don't have any failing tests there. Can you provide instructions on how to reproduce the test failures?

**Comment by jrief** [comment]
Then we can close this issue.
