### ISSUE TITLE
Plugin Permissions

### ISSUE THREAD

**Issue by darbula** [jrief/djangocms-cascade#169]
It is not clear what is the right procedure for adding permissions to non superusers to let them edit plugins. Currently `cms.utils.permissions.has_plugin_permission` is checking if user has certain permission, i.e. `cmsplugin_cascade.change_bootstrappicturepluginmodel`, and returning `False`.

**Comment by jrief** [comment]
do fine grained do you need permissions? On the plugin-level, or is it enough on a group of plugins, say all Bootstrap plugins.
Can you give me an example of what should be possible and what should be forbidden for a small set of users.

**Comment by darbula** [comment]
Currently I need just to allow regular non superusers to add, change and delete all cascade bootstrap plugins, so it is definitely on the group-of-plugins level.

OTH it is not difficult to imagine situations in which plugin level is needed, although page level permissions and cms placeholder config can help a lot in such usecases.

**Comment by jrief** [comment]
But they are staff users, do they?

**Comment by darbula** [comment]
Yes, they are.

**Comment by rfleschenberg** [comment]
I'll take a look at this ASAP.

**Comment by jrief** [comment]
Fine grained permissions have been added into version 0.12

**Comment by darbula** [comment]
Great, thanks!
