### ISSUE TITLE
HTMLParser instance has no attribute 'html'

### ISSUE THREAD

**Issue by khrizo** [jrief/djangocms-cascade#181]
**Exception Value:**
HTMLParser instance has no attribute 'html'
Exception Location: /local/lib/python2.7/site-packages/cmsplugin_cascade/bootstrap3/carousel.py in get_form, line 139
Python Version: 2.7.6

removing the html attr works fine, should that not be there?

```
    def get_form(self, request, obj=None, **kwargs):
        if obj:
            caption = self.html_parser.html.unescape(obj.glossary.get('caption', ''))
            obj.glossary.update(caption=caption)

```

**Comment by jrief** [comment]
This was due to some version mismatch in htmlparser.
A fast fix is to replace ``self.html_parser.html.unescape`` against ``self.html_parser.unescape``.

**Comment by khrizo** [comment]
Yes, that's what I did.
Thanks.
