### ISSUE TITLE
segmentation cms_plugins.py get_render_template accesses undefined variables in case of uncaught exception

### ISSUE THREAD

**Issue by kernom** [jrief/djangocms-cascade#185]
I.e. when:  eval_template.render(context) == 'True' throws a non TemplateSyntaxError two variables are undefined but accessed in the finally black.

Note, further line 94 uses the deprecated has_change_permission(request), this could be trivially fixed with has_change_permission(request.user) for now(which I have done in my case), but that is deprecated as well and should probably use the version in cms.utils.page_permissions ( http://docs.django-cms.org/en/latest/upgrade/3.4.html?highlight=cms.utils.page_permissions )
edit_mode = (toolbar and toolbar.edit_mode and placeholder.has_change_permission(request.user)

See below for a trivial fix (excluding the permission part):
diff -r 4fdfb64776a0 lib/python3.4/site-packages/cmsplugin_cascade/segmentation/cms_plugins.py
--- a/lib/python3.4/site-packages/cmsplugin_cascade/segmentation/cms_plugins.py	Wed Sep 21 10:15:15 2016 +0700
+++ b/lib/python3.4/site-packages/cmsplugin_cascade/segmentation/cms_plugins.py	Wed Sep 21 10:39:47 2016 +0700
@@ -61,13 +61,15 @@
     def get_render_template(self, context, instance, placeholder):
         def conditionally_eval():
             condition = self.html_parser.unescape(instance.glossary['condition'])
+            evaluated_to = False
+            template_error_message = None
             try:
                 eval_template = Template(self.eval_template_string.format(condition))
                 evaluated_to = eval_template.render(context) == 'True'
-                template_error_message = None
+                
             except TemplateSyntaxError as err:
                 # TODO: render error message into template
-                evaluated_to = False
+                
                 template_error_message = err.message
             finally:
                 if evaluated_to:

**Comment by jrief** [comment]
Could you please create a pull request for this. It would be much easier for me to merge.

**Comment by kernom** [comment]
done .. twice it seems, sorry.
