### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by georgema1982** [jrief/djangocms-cascade#19]
I see a deprecation warning:

DeprecationWarning: please rename the table "cmsplugin_cascadeelement" to "cmsplugin_cascade_cascadeelement" in cmsplugin_cascade
The compatibility code will be removed in 3.1
  table_name, old_db_name, model._meta.app_label), DeprecationWarning)

Dependencies:

Django==1.6.2
South==0.8.4
django-cms==3.0
djangocms-cascade==0.3.0

Also, dumpdata command fails with the following error: CommandError: Unable to serialize database: relation "cmsplugin_cascade_cascadeelement" does not exist

**Comment by rfleschenberg** [comment]
I think this issue is most likely outdated and not applicable anymore. If I am wrong, please open a new issue.
