### ISSUE TITLE
Cannot edit slide

### ISSUE THREAD

**Issue by sproctor** [jrief/djangocms-cascade#192]
ImproperlyConfigured at /en/admin/cms/page/edit-plugin/115/
A CarouselSlidePlugin requires a valid parent

cmsplugin_cascade/bootstrap3/carousel.py in get_form, line 144

The slide appears to have a valid parent. I can't understand why get_parent_instance on line 142 is returning None.

**Comment by jrief** [comment]
This is weird. Can you please retry with the configuration settings from example.py

**Comment by jrief** [comment]
From examples/settings.py

**Comment by sproctor** [comment]
I tried copying most settings from settings.py, still the same issue. I tried running the bs3demo, there's a bit of a lack of documentation. When I do, I get this error:

ImportError: No module named 'cmsplugin_cascade.segmentation.settings'

Could be because djangocms-cascade installed is from pip, the bs3demo is from git?

BTW, this happens when trying to edit both column and slide, but row and carousel work fine.

**Comment by jrief** [comment]
did you add ``'cmsplugin_cascade.segmentation',`` to your INSTALLED_APPS?

btw. the bs3demo only runs from github, because the PyPI package does not contain any example code. Therefore you should not mix these versions.

**Comment by jrief** [comment]
have you been able to solve it?

**Comment by sproctor** [comment]
'cmsplugin_cascade', 'cmsplugin_cascade.clipboard',  'cmsplugin_cascade.extra_fields',  'cmsplugin_cascade.sharable',  and 'cmsplugin_cascade.segmentation' were in my INSTALLED_APPS.

This seemed to work:

```
CMS_PLACEHOLDER_CONF = {
    'content': {
        'parent_classes': {'BootstrapContainerPlugin': None,},
    },
}
```

This did not show up:

```
CMS_PLACEHOLDER_CONF = {
    'Main Content Placeholder': {
        'plugins': ['BootstrapContainerPlugin'],
        'text_only_plugins': ['TextLinkPlugin'],
        'parent_classes': {'BootstrapContainerPlugin': None},
        'glossary': {
            'breakpoints': ['xs', 'sm', 'md', 'lg'],
            'container_max_widths': {'xs': 750, 'sm': 750, 'md': 970, 'lg': 1170},
            'fluid': False,
            'media_queries': {
                'xs': ['(max-width: 768px)'],
                'sm': ['(min-width: 768px)', '(max-width: 992px)'],
                'md': ['(min-width: 992px)', '(max-width: 1200px)'],
                'lg': ['(min-width: 1200px)'],
            },
        },
    },
}
```

I also had:

```
CMSPLUGIN_CASCADE_PLUGINS = ('cmsplugin_cascade.bootstrap3',)
CMSPLUGIN_CASCADE = {
    'alien_plugins': ('TextPlugin', 'FilerImagePlugin', 'OtherLeafPlugin',),
}
```

**Comment by jrief** [comment]
And what is the name of the ``{% placeholder ??? %}`` in your template?

**Comment by sproctor** [comment]
It's "content". Sorry, I'm a new to Django CMS and I didn't realize I needed to change that. Let's ignore that second try. I got the error when I had both that and this one:

```
CMS_PLACEHOLDER_CONF = {
    'content': {
        'parent_classes': {'BootstrapContainerPlugin': None,},
    },
}
```
