### ISSUE TITLE
Please test upcoming version 0.11.0

### ISSUE THREAD

**Issue by jrief** [jrief/djangocms-cascade#193]
Version 0.11.0 contains a major change in the way plugin classes are declared:

Instead of adding a list of `PartialFormField`s named `glossary_fields`, we now can add these
fields to the plugin class, as we would in a Django `forms.Form` or `models.Model`, for
instance

``` python
class MyPlugin(CascadePluginBase):
    name = "My Plugin"
    ... other attributes ...
    some_attr = GlossaryField(a_widget, label="A Label", initial=some_value)
```

instead of

``` python
class MyPlugin(CascadePluginBase):
    name = "My Plugin"
    ... other attributes ...
    glossary_fields = (
        PartialFormField('some_attr', a_widget, label="A Label", initial=some_value),
    )
```

What's your opinion about it?

BTW: this feature is available on branch `glossary_fields`

**Comment by racitup** [comment]
Looks great and much more djangoic! I've been looking at the source recently and did think the glossary_fields = (PartialFormField, ...) looked like a bit of a hack.

I assume the old style will still be supported if you merge this change into master?

Also, can I ask why it's called a GlossaryField and not something like CascadeField/ElementField/StoredField?

**Comment by jrief** [comment]
The old style is supported as well, but deprecated.

> Also, can I ask why it's called a GlossaryField and not something like CascadeField/ElementField/StoredField?

Very good question and I was struggling finding a good name for it.

"Glossary" is not my first choice, but "context" and "scope" have already been used. "data" is too generic. So "glossary" was a good fit. We then discussed what would be the best name, and since the list of ...Fields is named glossary_fields, the best choice was ``GlossaryField``. There is also little chance for naming conflicts.
