### ISSUE TITLE
classes... am I missing something?

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#194]
Hi, I hope it's okay to post a question here rather than an issue like it says in the docs...

I'm attempting to implement a website using the CMS (because it's a derivative of Django SHOP) and have purchased a CSS styling kit based on Bootstrap3 and Google's Material Kit that I am trying to use. It has a lot of pre-defined classes that I am trying to apply to cascade plugins for relatively static content in the CMS (e.g. About, Contact, etc) but I can only find ways to specify the Element ID (e.g. on the Simple Wrapper plugin). Below is an example.

Is there a setting that I'm missing that switches the Element Class on for the plugins, or am I missing the point entirely?

```
<div class="card card-profile card-plain">
  <div class="card-avatar">
    <a href="#pablo">
      <img class="img" src="../assets/img/faces/marc.jpg">
    </a>
  </div>

  <div class="content">
    <h4 class="card-title">Alec Thompson</h4>
    <h6 class="category text-muted">CEO / Co-Founder</h6>

    <p class="card-description">
      And I love you like Kanye loves Kanye. We need to restart the human foundation.
    </p>
    <div class="footer">
      <a href="#pablo" class="btn btn-just-icon btn-simple btn-twitter">
        <i class="fa fa-twitter"></i>
      </a>
      <a href="#pablo" class="btn btn-just-icon btn-simple btn-facebook">
        <i class="fa fa-facebook-square"></i>
      </a>
      <a href="#pablo" class="btn btn-just-icon btn-simple btn-google">
        <i class="fa fa-google"></i>
      </a>
    </div>
  </div>
</div>
```

**Comment by racitup** [comment]
Okay, so I'm guessing the way to solve this is to wrap the style kit SCSS with my own SCSS making liberal use of the `@extend` directive like so?

```
@import "../sass/material-kit";

// Apply styling to elements based on their hierarchy:
div.card-profile {
    +div {
        @extend .card-avatar;
        img {
          @extend .img
        }
    }
    ...
}
```
and
```
<!-- This line should be in the html template: -->
<div class="card card-profile card-plain">
  <div>
    <a href="#pablo">
      <img src="../assets/img/faces/marc.jpg">
    </a>
  </div>
...
```

**Comment by jrief** [comment]
keep in mind to configure ``SASS_PROCESSOR_INCLUDE_DIRS`` in your settings.py.

My experience with predefined BS3 styles is not very good. They often are optimized for one specific CMS, normally Wordpress and can hardly be used for anything else. 

You may send me these styles via email, so that I can have a look at them.

**Comment by racitup** [comment]
Thanks for the advice. I bought the pro version so wouldn't be comfortable sharing, but their free version is available on github. [Here's an example page](https://github.com/timcreative/material-kit/blob/master/examples/landing-page.html).

I've asked the creators and their suggestion is to try adding namespaces in SASS for a page/component like [here](https://coderwall.com/p/xdmceg/how-to-create-scoped-and-namespaced-css-using-sass). My main concern is that using extensive use of @extend could create huge css files which would give the browser a hard time? But this suggestion seems to address that fear nicely. Just hope I can persuade the framework to minify the css automatically.
I assume the 'helper method' they mention in the post is a Ruby on Rails thing..

**Comment by racitup** [comment]
I'm making progress by wrapping the kit SASS with my own where necessary.

I haven't tried it but in case someone reads this for a similar issue, have a look at `DJANGO CMS CASCADE, Custom CSS classes and styles` in the Django admin interface..
