### ISSUE TITLE
Way to get rid of col-xs-12?

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#195]
Currently on djangocms-cascade==0.9.0

Is there a way to get rid of the default `col-xs-12` on a cascade bootstrap column?
It says in [this post](http://stackoverflow.com/a/26777591/1241499) that this is the default setting. I think it is implied that you have another `col-` class specified; a `<div>` with no col class is clearly _not_ a column.

I would suggest having a 'default' option in the 'Column width for mobile phones' setting which only adds `col-xs-12` if no other Column width option is specified..

An example rendering: `<div class="col-xs-12 col-md-8 col-md-offset-2">`

**Comment by jrief** [comment]
Something you can do, is to not activate the breakpoint for phones in your ContainerPlugin's settings.

Then that option doesn't even appear. Otherwise, for me it's hard to see a feasible way to remove that option. How would that work out in Bootstrap?

**Comment by jrief** [comment]
Did this help, can I close the issue?

**Comment by racitup** [comment]
Yes, disabling the container phone setting removes the "col-xs-12", so yes this is a solution and can be closed, thanks.

Weirdly, doing this also changes the tablet column width to 1 unit which is not reflected in the rendered html.
