### ISSUE TITLE
Partial Bootstrap Grid Placeholder

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#198]
Is it possible to configure a bootstrap placeholder that doesn't start with the `BootstrapContainerPlugin`?

I have a template which already has a `<div class="container">` and would like to put a Placeholder inside it with `BootstrapRowPlugin` as the first parent plugin.

**Comment by jrief** [comment]
Yes, and it's even documented somewhere (I don't remember the URL).
What you have to provide then, is the initial "glossary" using the CMS_PLACEHOLDER_CONF in yours settings. This is because the Cascade bootstrap system has to figure out the initial width for each column.

**Comment by racitup** [comment]
Found it, thanks!
http://djangocms-cascade.readthedocs.io/en/latest/bootstrap3/grid.html#adding-plugins-into-a-hard-coded-grid
