### ISSUE TITLE
OrderedDict problem with Python 3.5

### ISSUE THREAD

**Issue by perplexa** [jrief/djangocms-cascade#207]
When using cms-cascade with Python 3.5, the `SegmentPlugin.get_form` call fails due to return type changes in `OrderedDict.values`, which does not return a list anymore but instead an odict_values object. This object does not support index lookups anymore and thus needs to be converted to a list before accessing its items by index.

The incompatible lines are here: https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/segmentation/cms_plugins.py#L135-L136

I submitted a pull request with a fix here: https://github.com/jrief/djangocms-cascade/pull/206

The issue can be reproduced by editing a CMS page, switching to 'structure' view and adding: container->simple wrapper->segment

**Comment by jrief** [comment]
closed via #206
