### ISSUE TITLE
'SortableInlineCascadeElementForm' object has no attribute 'glossary_fields' Exception when adding Gallery plugin

### ISSUE THREAD

**Issue by dboczek** [jrief/djangocms-cascade#208]
I have 'SortableInlineCascadeElementForm' object has no attribute 'glossary_fields' exception when trying to add Gallery plugin to page.

Using master branch.

My settings for cascade are:

```python
CMSPLUGIN_CASCADE_PLUGINS = (
    'cmsplugin_cascade.bootstrap3',
    'cmsplugin_cascade.link',
    'cmsplugin_cascade.generic',
)

CMSPLUGIN_CASCADE = {
    'alien_plugins': ('TextPlugin', 'SnippetPlugin'),
}

**Comment by jrief** [comment]
Could you please paste the full stacktrace on dpaste.de and send me this link.
Which version of Cascade are you using?

**Comment by pcolmant** [comment]
Hi Jacob,

To reproduce it on the master branch, I did : 

Add a container.
Add a row with 1 column.
Try to add a Gallery.

The type of the object which has no glossary_fields is django.forms.widgets.SortableInlineCascadeElementForm.

The error happend on line 48 in __init__ of bootstrap3/gallery.py into "for key in self.glossary_fields"

Patrick

**Comment by pcolmant** [comment]
This happend with or without  "django-admin-sortable2' installed.

Enclosing both 

for key in self.glossary_fields:
    ...

into a try / catch AttributeError seems to be a workaround.

**Comment by dboczek** [comment]
Full stacktrace: https://dpaste.de/RFFT
I'm using latest version from master.

**Comment by jrief** [comment]
I can reproduce this error. Seems to be a regression introduced in version 0.10. I'm currently attempting to fix it.

**Comment by jrief** [comment]
Please retest with this fix. I then will release a new version.

And if you come across a good template for a BS3-based image gallery, please let me know.

**Comment by dboczek** [comment]
Thanks and sorry for late reply. I confirm that it works right now.

As for BS-3 template for gallery unfortunately I don't have anything that would fit in this project right now.
