### ISSUE TITLE
[docs] Suggest lists instead of tuples in settings

### ISSUE THREAD

**Issue by bittner** [jrief/djangocms-cascade#214]
The documentation suggests using tuples for most of the settings, e.g. [Django's INSTALLED_APPS](http://djangocms-cascade.readthedocs.io/en/latest/installation.html#configure-the-cms-plugin), [Cascade plugins](http://djangocms-cascade.readthedocs.io/en/latest/installation.html#activate-the-plugins), [leaf plugins](http://djangocms-cascade.readthedocs.io/en/latest/installation.html#define-the-leaf-plugins).

Now even Django core has switched to the (I think, semantically correct) use of lists in Python for everything that is of the same type (I believe), e.g. [INSTALLED_APPS](https://docs.djangoproject.com/en/1.10/ref/settings/#installed-apps). Could the Cascade docs also suggest using lists instead of tuples where appropriate? Technically, it works in the code, as for what I have tried.

I'd prepare a PR for the docs, if that's alright.

**Comment by jrief** [comment]
Thanks for the hint. After looking for references to this claim, I came across this post on [Stackoverflow](http://stackoverflow.com/questions/36081149/why-did-django-1-9-replace-tuples-with-lists-in-settings-and-urls/36081236) which states that once the documentation said: "For settings that are sequences, use tuples instead of lists. This is purely for performance."

This doesn't seem to be true anymore. Therefore in one of my next versions I'll have to refactor this.

**Comment by bittner** [comment]
Another thought:

What about refactoring `CMSPLUGIN_CASCADE_PLUGINS` into `CMSPLUGIN_CASCADE['plugins']`? Would that be an option? This way we'd only have to define a single property for Cascade in Django's settings, e.g.
``` python
CMSPLUGIN_CASCADE = {
    'plugins': ['cmsplugin_cascade.bootstrap3'],
    'alien_plugins': ['TextPlugin'],
}
```
Would be a nice side-by-side of regular Cascade plugins and their alien friends.

**Comment by jrief** [comment]
Yes, another issue on my TODO-list.
Thanks for reminding me.

**Comment by jrief** [comment]
Settings in the examples have been changed now, hence closing.

**Comment by bittner** [comment]
There are still occurrences of tuples where lists could be  used, e.g.

- [Installation: Configure the CMS plugin](https://github.com/jrief/djangocms-cascade/blob/master/docs/source/installation.rst#configure-the-cms-plugin)
- [Installation: Define the leaf plugins](https://github.com/jrief/djangocms-cascade/blob/master/docs/source/installation.rst#define-the-leaf-plugins)
