### ISSUE TITLE
Django-1.10, django-cms-3.4 and djangocms-text-ckeditor-3.3

### ISSUE THREAD

**Issue by jrief** [jrief/djangocms-cascade#215]
Finally I got a version of djangocms-cascade which works with Django-1.10, django-cms-3.4 and djangocms-text-ckeditor-3.3

Please help me to test it in your environment and share your experience:

Install Cascade from branch compat-ckeditor-3.2

Install Django-1.10.4

Install CMS with a not yet merged patch:
```
pip install https://github.com/jrief/django-cms/archive/f9b62031f64aa7d775f9d1befa7b6a70d0d1a719.zip#egg=django-cms
pip install --upgrade --no-deps djangocms-text-ckeditor==3.3.1
```

Unfortunately the CMS introduced a bunch of incompatible API changes, hence upcoming version of Cascade (0.12) will only work with django-CMS version 3.4, whereas version 0.11 will continue to work with django-CMS version 3.3.

@pcolmant sorry for not getting back, but I was too busy on this migration. Would be great if you could test this.

**Comment by pcolmant** [comment]
Thank you very much Jacob for your work,

I will make tests during this week-end.

**Comment by jrief** [comment]
Now the unit tests also pass.
Please use the dependencies as specified there, specially my version of the CMS.

BTW, the CMS must determine the parent-children relationship of plugins in a more dynamic way. 
Hence I created a PR https://github.com/divio/django-cms/pull/5809 , which was rejected. Please read the whole thread and add your two cents. It's quite important for Cascade, and maybe other use-cases.

Otherwise, I'd have to monkey-patch the CMS; something I absolutely hate to do.

**Comment by jrief** [comment]
Please also leave your comments here: 
https://plus.google.com/u/0/+JacobRief/posts/4moFBcDqpT1?sfc=true

**Comment by electroniceagle** [comment]
Does this resolve the get_parent_classes() change from object method to class method?
https://github.com/divio/django-cms/blob/593968328e91b43516916d2235863ce5cdf24435/cms/plugin_base.py#L441

**Comment by jrief** [comment]
you still have to install django-cms from

https://github.com/jrief/django-cms/archive/fixes/flexible-parent+child_classes.zip#egg=django-cms

until this PR integrated
