### ISSUE TITLE
Jumbotron, image background in Safari.

### ISSUE THREAD

**Issue by khrizo** [jrief/djangocms-cascade#216]
I have a jumbotron with an image background which works fine in FF and GC, however in Safari (version 10.0.2 - 12602.3.12.0.1) the image doesn't show.

I believe the issue is in the media query:

`@media(min-width: 1200px) and (min-resolution: 1.5dppx)`

Works fine removing (min-resolution: 1.5dppx).

Test the browser media queries with this script http://jsfiddle.net/stopsatgreen/pKrZv/

This could be used instead?

`@media("width declaration") and (min-resolution: 1.5dppx), (min-resolution: 144dpi), (-webkit-min-device-pixel-ratio: 1.5), (-o-min-device-pixel-ratio: 3/2) {}`

**Comment by jrief** [comment]
Thanks for reporting.
Would you mind to create a pull request?

**Comment by jrief** [comment]
@khrizo 
In version 0.12 I'm going to replace your patch

```
@media("width declaration") and (min-resolution: 1.5dppx), (min-resolution: 144dpi), (-webkit-min-device-pixel-ratio: 1.5), (-o-min-device-pixel-ratio: 3/2)
```

against

```
backgound-image: url(lowres.jpg); 
backgound-image: image-set(url(lowres.jpg) 1x, url(highres.jpg) 2x);
```

because it created a lot of weird issues, especially with the Carousel plugin. Could you please confirm, that this isn't a problem for you.

This is the change: https://github.com/jrief/djangocms-cascade/commit/44b4e222cb6df90d0dbe58a2e899df6097d03cba

**Comment by khrizo** [comment]
@jrief 
Tested it, works fine on my end, see below.

On a side note: Just check the typo django-mptt=0.8.7 in requirements/base. I was also getting an error (RuntimeError: Couldn't call pandoc to get output formats. Output from pandoc:) installing pypandoc==1.2.0 in requirements/develop,
I ended up removing ==1.2.0 and just install pypandoc

**Comment by jrief** [comment]
Thanks for testing.

About pypandoc. That is only required during development, so I'm wondering when this happened?
I'd prefer to have this dependency optional.

**Comment by khrizo** [comment]
while doing $: pip install -r requirements/develop
