### ISSUE TITLE
Please test upcoming version 0.12rc1

### ISSUE THREAD

**Issue by jrief** [jrief/djangocms-cascade#226]
Today I released version 0.12. It supports Django-1.10 and Django-CMS-3.4 and is one major step forward. These are all the changes:

* Added compatibility for Django version 1.10.
* Added compatibility for django-CMS version 3.4.
* Added monkey patch to resolve issues handled by PR https://github.com/divio/django-cms/pull/5809
* Added compatibility for djangocms-text-ckeditor-3.4.
* **Important for AngularJS users**: Please upgrade to angular-ui-bootstrap version 0.14.3. All
  versions later than 0.13 use the prefix ``uib-`` on all AngularJS directives, hence this upgrade
  is required.
* In the ``CarouselSlide`` plugin, caption is added as a child ``TextPlugin`` instead of using the
  glossary. Currently the migration of ``TextLinkPlugins`` inside this caption field does not work
  properly. Please create an issue, if you really need it.
* Added method ``value_omitted_from_data`` to ``JSONMultiWidget`` to override the Django method
  implemented in ``django.forms.widgets.MultiWidget``.
* In ``cmsplugin_cascade.models.CascadeElement`` the foreign key ``shared_glossary`` now is marked
  as editable. Instead to plugins without sharable glossary, the attribute
  ``exclude = ['shared_glossary']`` is added.
* Instead of handling ring.js plugin inheritance through ``get_ring_bases()``, Cascade plugins
  just have to add ``ring_plugin = '...'`` to their class declaration.
* Function ``cmsplugin_cascade.utils.resolve_dependencies`` is deprecated, since Javascript
  dependencies now are handled via their natural inheritance relation.
* The configuration option ``settings.CMSPLUGIN_CASCADE['dependencies']`` has been removed.
* Added method ``save()`` to model ``SharedGlossary``, which filters the glossary to be stored to
  only those fields marked as sharable.
* Accessing the CMS page via ``plugin_instance.page`` is deprecated and has been replaced by
  invocations to ``plugin_instance.placeholder.page``.
* Removed directory ``static/cascade/css/fonts/glyphicons-halflings``, since they are available
  through the Bootstrap npm packages.
* All Javascript files accessing a property ``disabled``, now use the proper jQuery function
  intended for it.
* Added interface to upload fonts and use them as framed icons, text icons or button decorators.
* The permission system now is fine grained. Administrators can give their staff users
  add/change/delete permissions to each of the many Cascade plugins. When adding new plugins, this
  does not even require a database migration.
* Fixed: On saving a **CarouselPlugin**, the glossary of it's children, ie. **CarouselSlidePlugin**,
  is sanitized.
* Handle the high resolution of the **PicturePlugin** through ``srcset`` rather than a ``@media``
  query.
* Handle the high resolution background of the **JumbotronPlugin** through ``image-set`` rather than
  a ``@media`` query.

**Comment by bittner** [comment]
Works fine for me (with djangocms-cascade==0.12rc1, django-cms==3.4.2, but Django==1.9.12).

I only noticed I now have to install django-filer explicitly (i.e. add to my `requirements.txt`), not sure why.

**Comment by jrief** [comment]
Strange!
``django-filer`` is part of requirements/base.txt and should be installed by default, if you do ``pip install -r requirements/django19.txt``

**Comment by bittner** [comment]
I don't reference `requirements/django19.txt` explicitly (should I? [I follow the docs](http://djangocms-cascade.readthedocs.io/en/latest/installation.html)). I only add Cascade to my project `requirements.txt` (`djangocms-cascade>=0.12rc1`, currently) and rebuild my application container with Docker (the Dockerfile installs all dependencies from my requirements file).

Hence, everything that is referenced as dependency in [setup.py](https://github.com/jrief/djangocms-cascade/blob/master/setup.py#L38) is installed in addition, everything else not. Looks like django-filers was referenced/installed by some other package in the past. :worried:

**Comment by jrief** [comment]
OK, got it!
Not all of the plugins require django-filer, only Image, Picture, Jumbotron and FontIcons, hence I didn't want to add it as mandatory requirement.
I don't believe there is a feasible way, to only require 3rd party packages under certain conditions.

**Comment by haricot** [comment]
python==3.6.0 
django-cms==3.4.2
django==1.10.5

With this config : 
setup.py don't work (error pandoc), but work if you comment on the line line 42 in setup.py `#long_description=convert('README.md', 'rst'),`

plugin secondary_menu don't work for me, that is why I propose a  PR #225
Container/Row/Column/Secondary Menu

**Comment by bittner** [comment]
@jrief Re django-filer: It's fine as it is. Maybe this fact should be mentioned in the installation docs. It's not a real issue otherwise.

**Comment by jrief** [comment]
Thanks for testing, version 0.12 is released.
