### ISSUE TITLE
BootstrapSecondaryMenuPlugin loses configuration on update

### ISSUE THREAD

**Issue by rfleschenberg** [jrief/djangocms-cascade#229]
After upgrading to 0.12rc1, the `BootstrapSecondaryMenuPlugin` loses the setting for the `unstyled` template and renders as default. Explicitly adding this in my project settings works around the issue:

```
CMSPLUGIN_CASCADE['plugins_with_extra_render_templates'].setdefault('BootstrapSecondaryMenuPlugin', (
    ('cascade/bootstrap3/secmenu-list-group.html', _("default")),
    ('cascade/bootstrap3/secmenu-unstyled-list.html', _("unstyled")),
))
```

The state in the DB doesn't seem to be affected (after changing my project settings, it works).

**Comment by jrief** [comment]
please recheck with the latest version from GitHub
