### ISSUE TITLE
SimpleWrapperPlugin 'NoneType' object has no attribute 'cascadepage'

### ISSUE THREAD

**Issue by khrizo** [jrief/djangocms-cascade#237]
trying the impatient install before a brand new install `http://djangocms-cascade.readthedocs.io/en/latest/impatient.html#create-a-python-virtual-environment`

1. Add a new static_placeholder in the base.html template. 
`{% static_placeholder "demo" %}`

2. Try to add a SimpleWrapperPlugin in the new static placeholder.
`Exception Value: 'NoneType' object has no attribute 'cascadepage'`

**Comment by khrizo** [comment]
seems to happen in 0.11.3 as well.

**Comment by typefj** [comment]
add plugins_with_bookmark plugins to Static Placeholders will raise this error. Because Static Placeholder is not bound to any page or model, I temporarily fix it just ignore this error if placeholder obj no page.

**Comment by jrief** [comment]
In 0.14, I changed some parts of it. Please retest with that version.
