### ISSUE TITLE
SegmentPlugin loses choices?

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#242]
I'm currently having a problem with the SegmentPlugin whereby it loses the if, else options in the dropdown, see below. It was working and don't know how it broke..
`djangocms-cascade==0.12.5`

![screen shot 2017-06-20 at 15 55 23](https://user-images.githubusercontent.com/18157195/27339980-2ee60bb6-55d1-11e7-9829-38425e03a499.png)

**Comment by jrief** [comment]
If you move the plugin in the DOM tree, you have to reload the page.
What happens, if you publish and reload the pages?

If that doesn't help, please dump the placeholder's content as JSON and send it to me.

**Comment by racitup** [comment]
Thanks for the fast response.
The page is published and I have tried reloading.
I get no conditions when editing an existing Segment plugin or trying to add a new one.
How would I dump a placeholder? I can figure out which id it has from the db, but not sure how to run the serializer on it.. DRF `/?format=api` doesn't seem to work..

**Comment by jrief** [comment]
Dumping a placeholder:
* Go the context menu of the placeholder
* Select **Copy all**
* In Admin, go to **HOME > Django CMS Cascade > Persisted Clipboard Content**
* Add an entity
* Click on **Insert Data**
* From the **Data** text field, copy the JSON to the clipboard and paste it on https://dpaste.de
* Send me the link

**Comment by racitup** [comment]
This problem seems to have fixed itself! I'm not sure what I did, I think maybe just a runserver restart.
In case it helps [here's the placeholder dpaste](https://dpaste.de/KeN8)

**Comment by jrief** [comment]
Please keep an eye on it. If you can give me instructions on how to reproduce it, I might find the error. Otherwise it might have been cosmic radiation.
