### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: No class implements abstract base model: `BaseCustomer`.

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#248]
I have upgraded to `djangocms-cascade==0.14.1` & `django-shop==0.11.dev0` but now have the following error traceback. From the traceback it seems to be trying to use the Customer model before it is in the registry. The customer model does exist, I didn't have this error before upgrading.

The chain seems to be _cmsplugin-cascade -> customer form -> deferred customer model_

I've tried a different INSTALLED_APPS order and get a `django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.`

Do I need to make the customer form lazy?

> Traceback (most recent call last):
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/template/utils.py", line 65, in __getitem__
>     return self._engines[alias]
> KeyError: 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
>     django.setup()
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cmsplugin_cascade/models.py", line 208, in <module>
>     class IconFont(models.Model):
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cmsplugin_cascade/models.py", line 220, in IconFont
>     font_folder = FilePathField(allow_files=False, allow_folders=True)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cmsplugin_cascade/models.py", line 198, in __init__
>     kwargs.setdefault('path', app_settings.CMSPLUGIN_CASCADE['icon_font_root'])
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cmsplugin_cascade/app_settings.py", line 139, in CMSPLUGIN_CASCADE
>     settings_module = import_module('{}.settings'.format(module_name))
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/Users/rich/Documents/source/zbox-knightrider/CaseSolved_website/djangoshop-subscribe/shop_subscribe/cmsplugin_cascade.py", line 10, in <module>
>     from shop.cascade.plugin_base import DialogFormPluginBase, ShopLinkPluginBase, ShopLinkElementMixin
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop/cascade/plugin_base.py", line 21, in <module>
>     from cmsplugin_cascade.plugin_base import CascadePluginBase
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cmsplugin_cascade/plugin_base.py", line 27, in <module>
>     from .hide_plugins import HidePluginMixin
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cmsplugin_cascade/hide_plugins.py", line 12, in <module>
>     class HidePluginMixin(object):
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cmsplugin_cascade/hide_plugins.py", line 17, in HidePluginMixin
>     suppress_template = engines['django'].from_string('')
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/template/utils.py", line 80, in __getitem__
>     engine = engine_cls(params)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in __init__
>     options['libraries'] = self.get_templatetag_libraries(libraries)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
>     libraries = get_installed_libraries()
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
>     for name in get_package_libraries(pkg):
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
>     module = import_module(entry[1])
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/Users/rich/Documents/source/zbox-knightrider/CaseSolved_website/djangoshop-subscribe/shop_subscribe/templatetags/subscribe_tags.py", line 3, in <module>
>     from ..forms import SubscribeForm, ConfirmForm_factory
>   File "/Users/rich/Documents/source/zbox-knightrider/CaseSolved_website/djangoshop-subscribe/shop_subscribe/forms.py", line 10, in <module>
>     from shop.forms.checkout import CustomerForm
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop/forms/checkout.py", line 20, in <module>
>     class CustomerForm(DialogModelForm):
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/djng/forms/angular_base.py", line 248, in __new__
>     new_class = super(BaseFieldsModifierMetaclass, cls).__new__(cls, name, bases, attrs)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/forms/models.py", line 229, in __new__
>     if opts.model:
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/utils/functional.py", line 234, in inner
>     self._setup()
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop/deferred.py", line 214, in _setup
>     self._wrapped = getattr(self._base_model, '_materialized_model')
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop/deferred.py", line 182, in __getattr__
>     raise ImproperlyConfigured(msg.format(self.__name__))
> django.core.exceptions.ImproperlyConfigured: No class implements abstract base model: `BaseCustomer`.

**Comment by jrief** [comment]
Assure that your project  either imports ``shop.models.default.customer.Customer`` or creates its own Customer model.

Also assure, that if you access that ``Customer`` too early while bootstrapping your application, it could not be ready yet. Then you should use ``CustomerModel`` which is a lazy version of the final ``Customer`` model.

**Comment by electroniceagle** [comment]
Not sure if this is your issue, but we hit something similar when trying to load signals that had references to shop models.  They were tripping up on the deferred models.  The solution was to move the signals import into the ready() method of AppConfig like so:

```
class SessionCoreConfig(AppConfig):
    name = 'session_core'
    verbose_name = "session_core"

    def ready(self):
        import session_core.signals  # noqa

```

**Comment by racitup** [comment]
Thanks both, I've already done both of those.
It is fixed if I comment out this:
```
CMSPLUGIN_CASCADE_PLUGINS = [
    ...
    'shop.cascade',
#     'shop_subscribe.cmsplugin_cascade',  <-- HERE
]
```
[Can you see the problem?](https://github.com/racitup/djangoshop-subscribe/blob/master/shop_subscribe/cmsplugin_cascade.py)

**Comment by jrief** [comment]
@electroniceagle you always have to do Django related imports in the `AppConf.ready()` method. This is not django-SHOP specific.

**Comment by jrief** [comment]
@racitup what exactly are you trying to do? Do you want to add an email field, where someone can add himself to be informed by a newsletter?
If you want, I can provide such a functionality on the current Customer model.

**Comment by racitup** [comment]
The shop_subscribe extension basically provides a form for submitting your email address, a confirmation email with a link, and a confirmation form where you can manage your subscriptions. The subscriptions are down to the webmaster to define in the customer model.

**Comment by jrief** [comment]
just to understand it right ...

> a confirmation email with a link

you mean: an email sent to the customer containing a link for confirmation?

>  a confirmation form where you can manage your subscriptions without logging in

how can you manage your profile without logging in?

> The subscriptions are down to the webmaster to define in the customer model.

please explain

**Comment by racitup** [comment]
Please have a look at the github module in the above link. Hopefully the readme explains it all.

**Comment by racitup** [comment]
It seems my problem was loading django-angular modelforms too early:

`from .forms import SubscribeForm, ConfirmForm_factory`

I fixed it by late-loading the relevant form class/factory using `import_string`

**Comment by racitup** [comment]
Seems to be fixed, closing
