### ISSUE TITLE
Checklist for custom plugins not showing?

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#251]
I'm having trouble getting a new plugin to show up in the CMS. Could anyone expand this list of things to check?
- The module containing the plugin is listed in CMSPLUGIN_CASCADE_PLUGINS
- CMS_PLACEHOLDER_CONF is configured to show the plugin
- The plugin is registered with `plugin_pool.register_plugin()`
- Ensure `parent_classes` defined in the plugin is compatible with your plugin hierarchy or override the setting in CMS_PLACEHOLDER_CONF
- If implementing a plugin that you need to be a child of `TextPlugin`:
  - Ensure `text_enabled = True`
  - Ensure `requires_parent_plugin ` returns `False`

Alternatively it would be great if `./manage.py cms check` could be improved tell you why some plugins don't appear.

I did find a good way to check a plugin is being loaded was to remove the `render_template` which would give an error, but even that isn't working now..

Edit: added items above..

**Comment by jrief** [comment]
Does the Plugin itself declare it's parents, for instance a list containing `BootstrapColumPlugin`?

**Comment by jrief** [comment]
> Alternatively it would be great if ./manage.py cms check could be improved tell you why some plugins don't appear.

This management command is part of Django-CMS, so it would have to be added there. However, such a command could be added to Cascade itself. Please open a feature request for it.

**Comment by racitup** [comment]
> Does the Plugin itself declare it's parents, for instance a list containing BootstrapColumPlugin?

Yes, it overrides this:
```
class LinkPluginBase(CascadePluginBase):
    allow_children = False
    parent_classes = []
    require_parent = False
    ring_plugin = 'LinkPluginBase'
```

**Comment by racitup** [comment]
Hmm, I think my problem is related to the plugin being a Link plugin..

**Comment by jrief** [comment]
Either set `parent_classes` to `None` or specify a list of plugins. 

The link plugins are trickier, since they are used by other plugins as mixing classes. Use the one provided in the demo-shop as a blueprint.

**Comment by racitup** [comment]
Thanks!

Looks like my plugin was missing both of:
```
    text_enabled = True

    @classmethod
    def requires_parent_plugin(cls, slot, page):
        """
        Workaround for `PluginPool.get_all_plugins()`, otherwise TextLinkPlugin is not allowed
        as a child of a `TextPlugin`.
        """
        return False
```
