### ISSUE TITLE
UncompressableFileError: '/media/icon_fonts/zaacev8d/fontello-bac65a64/css/fontawesome.css' isn't accessible via COMPRESS_URL

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#253]
I get the following error because icon_fonts are extracted to the media directory and so are not accessible for compression by django-compressor

> UncompressableFileError: '/media/icon_fonts/zaacev8d/fontello-bac65a64/css/fontawesome.css' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed

Can they be added to the ext-css block?

**Comment by jrief** [comment]
That should also work using the postprocessor ``shop.sekizai_processors.compress``. Just wondering how I handle this in Cascade without a dependency to django-shop.

**Comment by racitup** [comment]
Hmm, try to submit a PR to django-compressor and/or sekizai?
