### ISSUE TITLE
Support for bootstrap4.

### ISSUE THREAD

**Issue by electroniceagle** [jrief/djangocms-cascade#254]
Our team at Nimbis is starting to roll out a new theme that is built on bootstrap4.  Before we go crazy on a bootstrap4 directory tree, was wondering if other contributors have already started the migration.  There are a lot of changes that will spill into templates, different plugins, and admin view.

https://blog.getbootstrap.com

Thoughts on should we duplicate bootstrap3 directory and build a stand-alone bootstrap4 directory tree or try to override and inherit bootstrap3 from bootstrap4?  One thing that I notice that the templates directory for bootstrap3 is really in the wrong place.  It should not be in the top-level templates directory for the package.

**Comment by jrief** [comment]
I've seen one fork of this project in GitHub's "Insights", which seems to support BS4.
https://github.com/haricot/djangocms-cascade/tree/bs4/cmsplugin_cascade/bootstrap4
As I did not migrate my projects to BS4 yet, I've never tested it though.

In case you want me to setup and maintain BS4 in Cascade, please consider to fund this project.

**Comment by jamtwister** [comment]
Doesn't you support bootstrap4 since version 0.17?

**Comment by jrief** [comment]
Yes, version 0.17 has full Bootstrap-4 support.
