### ISSUE TITLE
glossary datatype order deterministic for dumpdata

### ISSUE THREAD

**Issue by racitup** [jrief/djangocms-cascade#255]
In Django 1.9 the dumpdata json output was made deterministic by them using OrderedDict instead of normal dicts.
Now when doing git diffs on fixtures, all of the dict fields (and especially glossary and iconfont fields) in cmsplugin_cascade objects change order. It would be great if this could get the same treatment.

**Comment by jrief** [comment]
Django's dumpdata of a JSONField actually wraps the JSON inside a text-string inside JSON.
Cascade itself preserves ordering of dicts, wherever required. I however, can't influence the way Django creates fixtures.

Arguing that diffs of fixtures are difficult to read, presumably is a weak argument.

**Comment by racitup** [comment]
Sorry, are you saying this is an issue with [jsonfield](https://github.com/dmkoch/django-jsonfield/)?

It's the same argument [as here](https://code.djangoproject.com/ticket/24558).

**Comment by jrief** [comment]
Until Python-3.6 dicts are in random order, hence I would say, that this is a Python problem. 
The only solution is to use an ``OrderedDict``, which however, when serialized results in a list of 2-tuples.
I have no recommendation on this, maybe with Python-3.6 is solves by itself.
