### ISSUE TITLE
Usage with custom cascade plugins

### ISSUE THREAD

**Issue by glomium** [jrief/djangocms-cascade#26]
Hi,

can i use ``models.CascadeElement`` only with plugins that are not a part of djangocms-cascade?

The documentation says that I have to set CMS_CASCADE_PLUGINS and in ``cms_plugins.py`` you prepend ``cmsplugin_cascade`` to every plugin.

Best wishes,
Sebastian

**Comment by rfleschenberg** [comment]
Closing this, no user feedback in more than a year. @glomium, please feel free to open a new issue. Thanks!
