### ISSUE TITLE
ICON FONT ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by haricot** [jrief/djangocms-cascade#262]
This error appeared after upgrading version  >=0.14.1

Resolved by handing over.

`instance._cached_icon_font = IconFont.objects.get(id=instance.glossary['icon_font'] or 0 )
`

instead

https://github.com/jrief/djangocms-cascade/blob/1cb03d51df14888028e5c809627de3eca5d8fc6c/cmsplugin_cascade/icon/mixins.py#L94

```

**Comment by jrief** [comment]
I fixed it by also catching `ValueError`. Should work as well. Thanks for reporting.
