### ISSUE TITLE
If more than one CheckboxInput in plugin only the first seem work correctly.

### ISSUE THREAD

**Issue by haricot** [jrief/djangocms-cascade#264]
version 0.15.2 but I think this bug already exsited.
For example the accordion plugin and the second CheckboxInput:
If the first is coched ( Close others ) and we unchecked the second checkbox ( First panel open ), after we record, when we reopen the second, it is coched whereas it should not be.

Alternative, it works well with CheckboxSelectMultiple

**Comment by jrief** [comment]
are you using the jQuery or the AngularJS variant?

**Comment by haricot** [comment]
I just tested with jquery then with angular, the bug occurs in both cases in the modal of the plugin accordion.

**Comment by haricot** [comment]
The plugin behaves appropriately in the rendered page, but it is in modal configuration of the plugin that remains checked. 
In the modal of the plugin accordion, if ([x] Close others ) is ticked and that we uncheck ( [ ]First panel open ), after save, when we reopen of the modal plugin accordion, it is on always coched in the modal ( [x]First panel open )
Maybe the export json is not necessary because this is reproducible with the project example.
![20171204-155741_capture](https://user-images.githubusercontent.com/344493/33559243-7a66cdb4-d90c-11e7-9fb4-dedca5225b01.gif)

**Comment by jrief** [comment]
got it and fixed.

**Comment by haricot** [comment]
Many thanks! 
it's instructive.
