### ISSUE TITLE
html_tag_attributes(title target) only work with TextLinkPlugin

### ISSUE THREAD

**Issue by haricot** [jrief/djangocms-cascade#268]
Solution 1: add attributes directly in ImagePlugin, PicturePlugin :
```
html_tag_attributes = {'image_title': 'title', 'alt_tag': 'tag', 'title': 'title', 'target': 'target'}

```

Solution 2 : add this under html_tag_attributes in ImagePlugin, PicturePlugin

```
from jsonmerge import merge
html_tag_attributes = merge(html_tag_attributes, LinkPluginBase.html_tag_attributes)

```
Solution 3 : 

Create html_tag_attr_target = {'title': 'title', 'target': 'target'} and change templates, models_base.py mixins.py

Also carousel need html_tag_attributes.

What do you think?

**Comment by jrief** [comment]
I'll check this soon.

**Comment by haricot** [comment]
I just saw that the type of html_tag_attributes was a dict, so I suggest this PR if it suits you.
