### ISSUE TITLE
djangocms_text_ckeditor doesin't works after installing djangocms-cascade

### ISSUE THREAD

**Issue by chiracmut** [jrief/djangocms-cascade#279]
Hello jreif,

I'v installed djangocms-cascade in my project and after putting all cascade setting in my project setting, the text editor, in the placeholder, doesin't works. i don't see icon but i see the white window. 
thanks to the help.

**Comment by jrief** [comment]
Which versions of django-cms and djangocms-text-ckeditor?
Try with django-cms 3.4.5 and djangocms-text-ckeditor 3.4.0, this works for me.

**Comment by chiracmut** [comment]
I use djangocms 3.5, djangocms_text_ckeditor 3.5.3

**Comment by chiracmut** [comment]
ok.
If i add a Textplugin outside of Cascade element it doesin't work... 
But when i desactivate all cascade elements, i mean djangocms-cascade, it's work normaly.

**Comment by haricot** [comment]
Skin moono does not seem to work currently with djangocms_text_ckeditor 3.5.3, use deflaut in place (moono-lisa).
Comment moono and it should work:

```
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
#    'skin': 'moono',                                                                                                                                                                     
    'toolbar': 'CMS',
    'stylesSet': format_lazy('default:{}', reverse_lazy('admin:cascade_texticon_wysiwig_config')),
}
```

**Comment by jrief** [comment]
Thanks @haricot  for finding out!

**Comment by chiracmut** [comment]
Thanks @harico.
Now it works.
