### ISSUE TITLE
sharedglossary is not editable (Reverse for 'fetch_fonticons' not found.)

### ISSUE THREAD

**Issue by haricot** [jrief/djangocms-cascade#317]
For reproduce, after i set icon frame and set sharedglossary and when i edited via url : 
http://127.0.0.1:8000/admin/cmsplugin_cascade/sharedglossary/

```
NoReverseMatch at /admin/cmsplugin_cascade/sharedglossary/3/change/
Reverse for 'fetch_fonticons' not found. 'fetch_fonticons' is not a valid view function or pattern name.
```

**Comment by jrief** [comment]
Thanks for reporting. I'm able to reproduce.

**Comment by jrief** [comment]
since the iconfont must be selected per page rather than per plugin (as in former versions), this reverse lookup is obsolete now.
We only must take care that the selected icon does not become a sharable property, but who wants that?
