### ISSUE TITLE
Docs: fix example

### ISSUE THREAD

**Issue by darbula** [jrief/djangocms-cascade#325]
Example in [docs](https://djangocms-cascade.readthedocs.io/en/latest/installation.html#special-settings-when-using-the-textplugin) that includes `from cmsplugin_cascade.utils import format_lazy` should be replaced with `from django.utils.text import format_lazy`, also it should probably be `admin:cascade_texteditor_config` instead of `admin:cascade_texticon_wysiwig_config`.

**Comment by jrief** [comment]
thanks for informing me
