### ISSUE TITLE
Subject location on picture plugins not honored

### ISSUE THREAD

**Issue by darbula** [jrief/djangocms-cascade#328]
The problem is probably with [these lines](https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/utils.py#L202-L205) for bootstrap3 and [these](https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap4/picture.py#L156-L159) for bootstrap4 since `subject_location` ends up being either `None` or `bool` and not being `None` or `str` (subject location data) as intended. The solution might be something like this:

```py
    if hasattr(instance.image, 'subject_location') and 'subject_location' in resize_options:
        subject_location = instance.image.subject_location
    else:
        subject_location = None
```

**Comment by jrief** [comment]
I will check this, as soon as I have some time.

**Comment by jrief** [comment]
Please recheck with current version on GitHub.
I then will release 0.18.1.
Thanks for reporting.
