### ISSUE TITLE
Feature: Should let users define arbitrary style classes for Simple Wrapper plugin

### ISSUE THREAD

**Issue by georgema1982** [jrief/djangocms-cascade#34]
Right now it seems to me that Simple Wrappe can only have divs with thumbnail and jumbotron classes. I feel its functionalities pretty restricted by such hardcoding. I suggest that users should be able to either predefine some classes in settings.py so that they can choose from a list of styles (similar to this plugin: https://github.com/divio/djangocms-style) or they can enter wildcard class names when using this plugin.

**Comment by jrief** [comment]
Hi Brian,
I now added a fully working Jumbotron plugin to the Cascade library.
Please peer review this branch https://github.com/jrief/djangocms-cascade/tree/jumbotron-plugin and tell me about your experience. In https://github.com/jrief/djangocms-cascade/blob/jumbotron-plugin/docs/source/bootstrap3/other-components.rst there is some documentation.
