### ISSUE TITLE
Raise TypeError: Plural value must be an integer, got str

### ISSUE THREAD

**Issue by aa327635899** [jrief/djangocms-cascade#353]
position:    cmsplugin_cascade/bootstrap4/container.py", line 349, in get_identifier
content = ungettext_lazy("default width: {0} unit", "default width: {0} units", width).format(width)

use django==2.2.6 and django-cms==3.7.0

**Comment by jrief** [comment]
Please provide a description on how to reproduce this error.

**Comment by atiberghien** [comment]
Same issue here. Just after trying to add a row to a container.

**Comment by haricot** [comment]
Maybe, which version of python do you use ? 
I could not reproduce it.  (django==2.2.6 and django-cms==3.7.0)
what commands did you launch to initialize the project?
