### ISSUE TITLE
Invalid tags of an image after rendering TextImagePlugin

### ISSUE THREAD

**Issue by execut** [jrief/djangocms-cascade#397]
For example we has image for TextImagePlugin with attributes:
```
image_title: title value
alt_tag: alt value
```
result html:
```html
<img tag="alt value" ...>
```
expected result:
```html
<img alt="alt value" title="title value" ...>
```
I think alt doesn't work correctly because of a typo here:
https://github.com/jrief/djangocms-cascade/blob/dec776711185d0d7de76b0ca30d984732dc88d0f/cmsplugin_cascade/generic/text_image.py#L66

Title does not work due to the fact that here it is reassigned from the parent class:
https://github.com/jrief/djangocms-cascade/blob/dec776711185d0d7de76b0ca30d984732dc88d0f/cmsplugin_cascade/generic/text_image.py#L67

**Comment by jrief** [comment]
close via #398
