### ISSUE TITLE
Why not using postgres JSONField instead of plugin django-jsonfield?

### ISSUE THREAD

**Issue by svandeneertwegh** [jrief/djangocms-cascade#399]
I searched for 
`
from jsonfield.fields import JSONField
`

And replaced it with:
`
from django.contrib.postgres.fields import JSONField
`

And worked like a charm!

I am curious of what you guys think of this.

**Comment by jrief** [comment]
`django.contrib.postgres.fields.JSONField` is deprecated and has been replaced by `django.db.models.JSONField` available since Django-3.1 in djangocms-cascade-2.0.
