### ISSUE TITLE
0.4.2 Cascade plugin error 'module' object has no attribute 'replace'. (Python 3.x)

### ISSUE THREAD

**Issue by JeymyAV** [jrief/djangocms-cascade#41]
Hi,
I'm testing the pluging 0.4.0 Cascade and I have got the bellow error with python version 3.x:

0.4.0 Cascade plugin error 'module' object has no attribute 'replace' at cmsplugin_cascade\bootstrap3\container.py
At line 276:
 width = string.replace(obj.glossary.get('{0}-column-width'.format(bp), ''), 'col-{0}-'.format(bp), '')
string is deprecated in python 3.x
I did a quick fix with str function:
width = str.replace(obj.glossary.get('{0}-column-width'.format(bp), ''), 'col-{0}-'.format(bp), '')
and it worked. 

str function is python 2.7 and 3.x compatible.

So, can you apply and recheck my suggestion, please?

**Comment by JeymyAV** [comment]
Hi,
I have found this issue in the cascade version 0.4.0 and this issue is not fixed yet in the cascade 0.4.2 version.
This only happen with the python 3.x version.

Please, Jacob, can you fix it on the next release. It is only one line of code at: cmsplugin_cascade\bootstrap3\container.py at the line number 275.
To change string.replace by str.replace.

Thanks,

**Comment by jrief** [comment]
Please send a PR.

**Comment by JeymyAV** [comment]
Sorry, what is a PR? , a picture, a prove, a printscreen?

Well as a prove, I sent a link for some deprecated functions on python 3:

https://docs.python.org/2/library/string.html

Look at the point "7.1.6. Deprecated string functions", and look at the paragraph:
"...although they will not be removed until Python 3."

and at the end of the page you can find the "string.replace" function is in the list which means it is deprecated in python 3 and was removed.

**Comment by quater** [comment]
In this context, PR means "Pull Request". You will have to fork the project, make the intended changes and then ask Jacob Rief to consider it to merge into the main code line.

See this YouTube video for clarification.
http://youtu.be/YTbRzhQju4c

**Comment by JeymyAV** [comment]
Thank you quater for the clarification. I'll think about it.

**Comment by rfleschenberg** [comment]
AFAIK, this has been fixed. Thanks, @JeymyAV and @quater.
