### ISSUE TITLE
TypeError while editing SimpleWrapper

### ISSUE THREAD

**Issue by tasosalvas** [jrief/djangocms-cascade#414]
Hey there,

I'm trying to upgrade a site from `0.19` and bootstrap3 (django `1.11.29`, django-cms `3.5.4`) to `2.3.2` and bootstrap4 (django `3.2.13`, django-cms `3.10.1`).

On pages using `SimpleWrapper`, runserver errors out when I click the hamburger menu on the top right to edit the page's structure.

```
Error during template rendering
In template [...]/lib/python3.7/site-packages/cms/templates/cms/toolbar/dragitem.html, error at line 50
50 <span class="cms-dragitem-text" title="{{ plugin.plugin_type }} ID: {{ plugin.pk }}"><strong>{{ plugin.get_plugin_name }}</strong> {{ plugin.get_short_description }}</span>
```

The last few lines of the traceback:
```
  File "[...]/lib/python3.7/site-packages/cmsplugin_cascade/models_base.py", line 28, in __str__
    return self.plugin_class.get_identifier(self)
  File "[...]/lib/python3.7/site-packages/cmsplugin_cascade/generic/simple_wrapper.py", line 34, in get_identifier
    identifier = super().get_identifier(instance)
  File "[...]/lib/python3.7/site-packages/cmsplugin_cascade/generic/mixins.py", line 72, in get_identifier
    element_id = instance.glossary['element_id'][instance.language]
TypeError: string indices must be integers
```

Local vars of the last line:
```
__class__ <class 'cmsplugin_cascade.generic.mixins.SectionMixin'>
cls 	   <class 'cmsplugin_cascade.generic.simple_wrapper.SimpleWrapperPlugin'>
instance  <cmsplugin_cascade.generic.simple_wrapper.SimpleWrapperPluginModel id=6602 plugin_type='SimpleWrapperPlugin' object at 0x7f58ef55d588>
```

On pages that don't have a `SimpleWrapper` already, the structure toolbar opens up normally and I can add/edit items.

It also allows me to add a `SimpleWrapper`, then when I click "Save" I get the same `TypeError`. So it also happens on new instances.

I've been going through changelogs, addressing deprecation warnings and updating settings for a couple of days now, so I may very well be missing something simple.

Uh, what else:
* The site has i18n, two languages
* I haven't tried a fresh codebase or db, kinda tunnel visioned on making this one work atm :)
* I've updated the site's settings using the `bs4demo` as a reference
* I've created two dummy cms_plugins (`CarouselPlugin` and `CarouselSlidePlugin`) that render a static template in order to prevent an old bs3 carousel from crashing a page - but those are just on one page and seem to work fine
* Everything on the upgraded site seems to render just fine, including the `div`s produced by the wrappers.

That line in the mixin is set up to handle `KeyError`, so maaaybe I'm at an edge case where it should also handle `TypeError` and let `super` deal with it? The only weird thing about the site is i18n, though. I haven't tried it or delved too deep into the codebase - my current assumption is that I'm missing something obvious.

https://github.com/jrief/djangocms-cascade/blob/0cfcd2afed935e7b58e644bf5a3bcc1808403bbf/cmsplugin_cascade/generic/mixins.py#L70-L78

That's all, I think. Thanks for reading :). I'd be sooo relieved if you could point me in the right direction.

**Comment by jrief** [comment]
> I'm trying to upgrade a site from 0.19 and bootstrap3 (django 1.11.29, django-cms 3.5.4) to 2.3.2 and bootstrap4

Oh, this is a huge step.

From reading your question, there can be thousand of reasons why you run into these kinds of problems. They presumably aren't even related to this app. Unfortunately I can't help you here.

**Comment by jrief** [comment]
It's fixed now on HEAD.

**Comment by tasosalvas** [comment]
No, it's `True` and the whole site is in two languages.

Thanks for giving it some more thought, I replicated the problem on a fresh instance `bs4demo` project and I was preparing to open a new issue. It happens there as well. Python `3.7`, so poetry ends up installing django `3.2.14`, apart from that completely vanilla.
