### ISSUE TITLE
Copying row with columns loses width

### ISSUE THREAD

**Issue by julienp** [jrief/djangocms-cascade#54]
Steps to reproduce, using the reference installation as described in: http://djangocms-cascade.readthedocs.org/en/latest/impatient.html

1 Add a container to the placeholder
2 Add a row with some number of columns
3 Copy the row (At this point the width is already lost from the glossary)
4 Paste the row into the container
Result: The row has columns with unknown width

It looks like the problem is that since the row has no parent, the glossary will not contain the breakpoints from the container, and BootstrapColumnPlugin.sanitize_model will remove the width keys from the glossary.

A workaround is to add a 'clipboard' placeholder to CMS_PLACEHOLDER_CONF, with a glossary with breakpoints and container_max_widths.
```
'clipboard': {
    'glossary': {
        'breakpoints': ['xs', 'sm', 'md', 'lg'],
        'container_max_widths': {'xs': 750, 'sm': 750, 'md': 970, 'lg': 1170},
    }
}
```

Maybe there should be a default glossary to fallback to or maybe the breakpoints and container_max_widths should be copied to the column glossary when it's copied, but then it needs to be removed again when the row is pasted into another container with possibly different settings.

**Comment by jrief** [comment]
Thanks for reporting.
The correct behavior would be that as soon as that row is pasted below another Container, the widths are recalculated using ``sanitize_children``. This function then would have to be invoked from the ContainerPlugin, which apparently doesn't work.
Sorry for that, if you have some time, please try to dig into.

**Comment by julienp** [comment]
I looked some more into this, and fixing it on paste is actually to late. The row is copied to the clipboard placeholder and save (called by copying mechanism) will call sanitize_model. Since the clipboard placeholder has no glossary, the list of breakpoints is empty and all column information is removed because it's "obsolete".
The suggested fix only does the removal of obsolete information if there are actually some breakpoints on the root container.

**Comment by jrief** [comment]
Ok, then I'll have to add the glossary to the CMS directly.
For this I have convince the CMS maintainers, though.
Hope, they accept it.
