### ISSUE TITLE
Python 3.4 --> TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by jeroenvlek** [jrief/djangocms-cascade#56]
You probably dont' need the byte indicator anymore in Python 3:

File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cmsplugin_cascade/plugin_base.py", line 50, in create_model
    name += b'Model'

**Comment by jrief** [comment]
this has already been fixed

**Comment by jrief** [comment]
Thanks for reporting.
I just released 0.4.2 which contains that fix.
