### ISSUE TITLE
AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by jeroenvlek** [jrief/djangocms-cascade#57]
This was already mentioned in issue #52, but since it's a different issue, I decide to open a new thread.

I keep getting the above mentioned exception when trying to migrate the db or run a dev server (runserver) after installing the cascade plugin. I upgraded Django from 1.7.1 to 1.7.4, but to no avail. I took the settings directly from the bs3demo and integrated them into my own settings. I'm also using djangocms 3.0.9.

On a sidenote: I understand you probably have a lot to do, but you should know that the current docs have some holes in them (e.g. dependency for django-bootstrap3 vs cmsplugin_cascade.bootstrap3, CMS_CASCADE_PLUGINS, adding the plugin to MIGRATION_MODULES).

Please find my freeze below. If you need more info, for example a stacktrace or settings.py, please let me know. I didn't want to bloat the OP too much.

(datamantics_com)[jvlek@orochimaru datamantics.com]$ pip freeze
You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.                                                                        
bcrypt==1.1.0
cffi==0.8.6
cmsplugin-filer==0.10.1
dj-database-url==0.3.0
dj-static==0.0.6
Django==1.7.4
django-appconf==0.6
django-classy-tags==0.5.2
django-cms==3.0.9
django-filer==0.9.9
-e git://github.com/jeroenvlek/django-form-designer.git@71adc056e028efcb6e0a1303f798ea86ba9a715b#egg=django_form_designer-master
django-mptt==0.6.1
django-picklefield==0.3.1
django-polymorphic==0.6.1
django-reversion==1.8.5
django-sekizai==0.8.1
django-sslify==0.2.5
django-toolbelt==0.0.1
djangocms-admin-style==0.2.5
djangocms-cascade==0.4.2
djangocms-link==1.5
djangocms-picture==0.1
-e git://github.com/jeroenvlek/djangocms-revealjs.git@a81084228404a2b1f6ab0532fcbce5b74a6c2348#egg=djangocms_revealjs-master
djangocms-text-ckeditor==2.4.3
djangorestframework==3.0.2
easy-thumbnails==2.2
gunicorn==19.1.1
html5lib==0.999
jsonfield==1.0.0
Pillow==2.7.0
psycopg2==2.5.4
pycparser==2.10
pytz==2014.10
requests==2.5.1
sendgrid==1.2.0
shortuuid==0.4.2
six==1.8.0
smtpapi==0.1.2
South==1.0.2
static3==0.5.1
Unidecode==0.4.17
unittest2py3k==0.5.1

**Comment by jrief** [comment]
> On a sidenote: I understand you probably have a lot to do, 
True!

> but you should know that the current docs have some holes in them (e.g. dependency for django-bootstrap3 vs cmsplugin_cascade.bootstrap3, CMS_CASCADE_PLUGINS, adding the plugin to MIGRATION_MODULES).

I have to admit, that I never tried a migration with django-1.7
Currently django-select2 has an issue with django-1.7 and until this is solved, I stay with django-1.6
I'm also still on Py-2.7

Any help is welcomed. If you can confirm that django-select2 works/doesn't with django-1.7, then this would help me a lot.

**Comment by jeroenvlek** [comment]
Well, it's not just with migrate. It's also with runserver. 

I'll see if I can look into select2 (no clue what that is, but I'll google it).

**Comment by jrief** [comment]
django-select2 is the widget which helps to find the correct cms Page, when adding a link.
This works fine with django-1.6 but not with 1.7.

**Comment by jeroenvlek** [comment]
Ok, well I'm new to django-cms, but so far I've had no problems adding links without it. Maybe it's just not needed anymore in 1.7?

**Comment by jrief** [comment]
I just came across a similar issue today. Package Unidecode was missing.
Also, catching ImportErrors was not telling me about this problem.
This should be fixed now.

**Comment by jeroenvlek** [comment]
Thank you! Looking forward to 0.4.3 :)

**Comment by ngn1123** [comment]
@jeroenvlek Were you able to get rid of the exception? I'm also getting this same error. Here is my freeze:

Django==1.7.3
Django-Select2==4.2.2
Pillow==2.7.0
South==1.0.1
Unidecode==0.04.17
argparse==1.2.1
beautifulsoup4==4.3.2
cmsplugin-iframe==0.1.1
cmsplugin-zinnia==0.7
dj-database-url==0.3.0
django-blog-zinnia==0.15.1
django-classy-tags==0.5.1
django-cms==3.0.9
django-contrib-comments==1.5
django-filer==0.9.9
django-mptt==0.6.1
django-paypal==0.2
django-polymorphic==0.6.1
django-reversion==1.8.5
django-sekizai==0.8.1
django-tagging==0.3.4
django-xmlrpc==0.1.5
djangocms-admin-style==0.2.5
djangocms-cascade==0.4.2
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.1
djangocms-googlemap==0.2
djangocms-inherit==0.1
djangocms-installer==0.7.1
djangocms-link==1.5
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.4.3
djangocms-video==0.1
djangorestframework==3.0.3
easy-thumbnails==2.2
html5lib==0.999
ipython==2.3.1
jsonfield==1.0.0
psycopg2==2.5.4
pyparsing==2.0.3
pytz==2014.10
requests==2.5.1
six==1.9.0
wsgiref==0.1.2

**Comment by ngn1123** [comment]
I was able to determine that this AppRegistrynotReady error happens when you include the following two djangocms-plugins in your installed apps:

'djangocms_inherit',
'djangocms_link',

Once I removed these, I was able to migrate and use runserver. Just so whoever reads this knows, I am using Django 1.7.3, Django-Select2, and DjangoCMS 3.0.9.

**Comment by jeroenvlek** [comment]
No, because we have to wait for 0.4.3 ;)

**Comment by jrief** [comment]
'djangocms_inherit',
'djangocms_link',

don't make any sense with Cascade anyway.
Cascade adds its own LinkPlugin and the concept if inherit does not fit here.

**Comment by ngn1123** [comment]
You're absolutely right. That was an oversight on my part. 

@jeroenviek you have djangocms_link installed in your environment. I don't know if you are referencing it in Installed Apps, but if you are, make sure to remove it, and that error should stop occurring.

Thanks again Jacob for the great work you're doing. We all really appreciate it.

**Comment by jeroenvlek** [comment]
Indeed: Removing djangocms_link fixed it. Thanks :+1:

**Comment by creimers** [comment]
I can confirm that I had to remove both ``djangocms_link`` and ``djangocms_inherit`` to get it to work.
