### ISSUE TITLE
Bs3demo with Cascade 0.4.x the Bootstrap3 Navbar no works!

### ISSUE THREAD

**Issue by JeymyAV** [jrief/djangocms-cascade#61]
Hi,
I have followed all instructions from the documentation ("For the impatient") to do a quick install from the scratch and it seems work well because I can create pages and subpages with the menu option enable but a strange issue happen.

The Bootstrap3 Navbar no works and the page title no change.
I have investigate a little and seems that in the generated template is missing the bootstrap javascript.
I guess that the {% render_block "js" %} in the base template shoulb be added all javascript, but it's no happen.
I have to added it manually in the template and then the Bootstrap3 Navbar works.
I have to added manually this tag <title>{% block title %}Page Title{% endblock %}</title> in the same template and then the page title works again.
My question, 
Is this the normal procedure or this is an issue in this cascade version?
Or I have to take the default templates from the djangocms and added the missing tags that you said in the documentation?

Regards,
Jeymy

**Comment by jrief** [comment]
The impatient should work out of the box.
Did you install the bower components?

**Comment by jrief** [comment]
Just retested the installation instruction. Everything works as expected.

**Comment by JeymyAV** [comment]
Sorry Jacob, but this no works for me.
I have reinstalled again from the scratch following every step, one to one, as said the documentation "For the Impatient" and installing the bootstrap components using bower as said the documentation.
I don't change anything in the setting file or in the base template.
I have ran and have created one page and other subpage.
The Bootstrap3 Navbar no works and the page title no change, but bootstrip ccs file is loaded as you can see in the below picture:
![cascade issue](https://cloud.githubusercontent.com/assets/9624829/6327256/4082fb2c-bb5a-11e4-873f-e67cde4ddc78.jpg)
The bootstrap.js is in the same path as the bootstrap.css (bower_components\\bootstrap\\dist\\js\\)
My staticfiles_dirs is: 
STATICFILES_DIRS = (
    os.path.abspath(os.path.join(PROJECT_DIR, os.pardir, os.pardir, 'bower_components')),
)
and is working for css but not for the js.
Only works if I'm going to the base.html template and added the below tags:
{% addtoblock "js" %} <script type="text/javascript" src="{{ STATIC_URL }}jquery/dist/jquery.min.js"></script>{% endaddtoblock %}
{% addtoblock "js" %} <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/dist/js/bootstrap.min.js"></script>{% endaddtoblock %}
How it is possible that for you is working and for me no? Ok, maybe I am doing something wrong or maybe I have missing some steps... 
Please, can you help to find which step I have missed for my side?
Thank you.

**Comment by JeymyAV** [comment]
I was thinking in this issue and maybe the difference is that in your environment, in your browser maybe, you have something that when it detect that a javascript library is needed, automatically is downloaded from internet, and that is the reason because it is working for you.
You can check if I'm right using the network inspect or source inspect of your browser to find out if your javacript library is loaded from internet or from your static files.
What do you think about my theory?

**Comment by jrief** [comment]
Hmm, you are using Windows, right?
Do other Django apps run on Windows? Were you able to get djangoCMS up and running on Windows?

BTW: I don't work on Windows, but I know that this can cause some trouble. Therefore most Django developers use MacOS or Linux.

**Comment by JeymyAV** [comment]
Yes, I'm working with windows but this time we don't blame to uncle Billy! Ha,ha, ha,ha.
I think that I have found the problem. Sorry for insist too much on it but I think that the problem is in the base template used in the bs3demo.
This morning I have installed again the django-cms 3.0.10 without cascade but with bootstrap support. Bellow you can see that the base template contains the source for the bootstrap css and the javascript files:

![base template cms310](https://cloud.githubusercontent.com/assets/9624829/6330049/8e9f3a30-bb75-11e4-9a23-6e280f791e52.jpg)

The base template from the bs3demo contains the source for the bootstrap css but not for the  bootstrap javascript files.
So, It's impossible without the javascript files in the template, it can run, either linux, mac or windows.

The other issue, the page title, it is a bug on the CMS 3.0.10 (again other tag problem). I'll open a new issue for this in the djangoCMS place.

Finally, did I already convinced to you about the javascript issue?

**Comment by jrief** [comment]
This morning, @stefanfoulis and I retried to get the reference implementation up and running. We both succeeded without any problem.
If is doesn't work in your environment its probably because of air humidity or cosmic rays, but not because of a buggy application.
I won't comment on this anymore.
