### ISSUE TITLE
Docs example on "hard coded containers" leads to "KeyError"

### ISSUE THREAD

**Issue by lucaippo** [jrief/djangocms-cascade#66]
Documentation has a little tutorial to allow inserting a `BootstrapRowPlugin` directly into placeholders, if you already provide container in template (http://djangocms-cascade.readthedocs.org/en/latest/bootstrap3/grid.html#adding-plugins-into-a-hard-coded-grid)

Trying to use a `BootstrapImagePlugin` in such situation (placing it inside `BootstrapRowPlugin` > `BootstrapColumnPlugin` ) results in a `KeyError` being raised while accessing `glossary['media_queries']` (https://github.com/jrief/djangocms-cascade/blob/0.4.3/cmsplugin_cascade/bootstrap3/utils.py#L71).

This is solved using `bs3settings.py`'-like `CMS_PLACEHOLDER_CONF`, which defines `COLUMN_GLOSSARY`, which in turn defines `'media_queries'` and uses it for configuring the placeholder.

If I didn't miss anything, my proposal is to update the documentation to use a more complete glossary (maybe just copy-paste `COLUMN_GLOSSARY`). Let me know if you would like a PR for this.

Maybe there are other plugins that need these defaults when used outside a container, but `BootstrapImagePlugin` is the only one I found so far.

Cheers

**Comment by jrief** [comment]
Yes, a PR for the docs is welcomed.
Sorry for now having solved your problem with the panel groups yet.
