### ISSUE TITLE
When front-end editing (adding or adding rows for example) I get Internal server error

### ISSUE THREAD

**Issue by zanderle** [jrief/djangocms-cascade#68]
Whenever I do front-end editing, I get 500 error, saying 
```
The following error occured: RegistrationError at /en/admin/cms/page/add-plugin/ has not been registered with django-reversion Request Method: POST Request URL: http://localhost:8000/en/admin/cms/page/add-plugin/
```
The adding/editing still happens, but I get a notification and I can see it in the logs. Any ideas what is this?

**Comment by jrief** [comment]
django-reversion is not supported for the moment. Try to remove it from your dependencies, or even better, try to integrate it.

**Comment by zanderle** [comment]
@jrief thank you, that's helpful!

**Comment by miraculixx** [comment]
+1 same issue here, plus several others, trying at @0.4.5 with django cms 3.0 (e.g. it appears the static files are not installed on pip install). it's a pity, this plugin has great potential. I will make another attempt when I have more time...

**Comment by jrief** [comment]
can you please give me an example.
On your console you should see, if a file request results into a 404-error.

**Comment by furiousdave** [comment]
With regards to the assets when pip installing, I think you may just need to add that folder to your MANIFEST.in
recursive-include cmsplugin_cascade/static *

**Comment by rfleschenberg** [comment]
This should be fixed in current releases. Thanks!
