### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by zanderle** [jrief/djangocms-cascade#72]
In 0.5.0 changelog you wrote:
> Setting ``CASCADE_LEAF_PLUGINS`` has been replaced by ``CASCADE_ALIEN_PLUGINS``.

But in fact the setting should be ``CMSPLUGIN_CASCADE_ALIEN_PLUGINS`` (at least that's what's in the code)

Plus the documentation doesn't reflect this change (either of these two options).

I would fix it, but I am not sure whether you want to change the code or the documentation (and `README.md`)

Also, is there a reason why `'TextPlugin'` is always added? I think it would be better if you could override that.

**Comment by jrief** [comment]
Ups, that would be great.

Where do I add the TextPlugin by default?

**Comment by zanderle** [comment]
I'm sorry, I misread the code. TextPlugin is NOT added by default. My bad.

So what is correct `CASCADE_ALIEN_PLUGINS` or `CMSPLUGIN_CASCADE_ALIEN_PLUGINS`? Should I change the documentation or the code?

**Comment by jrief** [comment]
Oh! Have a look at the internal ``settings.py``
Internally I use ``CASCADE_ALIEN_PLUGINS `` but for an external setting, one must write ``CMSPLUGIN_CASCADE_ALIEN_PLUGINS ``. So the latter is the correct one for the docs.
