### ISSUE TITLE
How can I set offset for tiny devices?

### ISSUE THREAD

**Issue by zanderle** [jrief/djangocms-cascade#75]
There is no option to set `col-xs-offset` but I can set all the other offsets (sm, md, lg). Is there a reason for this?

**Comment by jrief** [comment]
Yes because BS does not define a ``col-xs-offset``.

... and btw., it doesn't make sense to offset content on a <768px device.

**Comment by zanderle** [comment]
Of course it does. Check out the [documentation](http://getbootstrap.com/css/#grid-options)

And it makes sense to use it. Very useful many times.

**Comment by jrief** [comment]
Ups, you're right!
I misunderstood the docs.
I will fix it.

**Comment by jrief** [comment]
Thanks for reporting

**Comment by zanderle** [comment]
Thanks for fixing :)
