### ISSUE TITLE
Reordering is not working properly

### ISSUE THREAD

**Issue by zanderle** [jrief/djangocms-cascade#76]
There is a bug when using column reordering.

For example: say I choose `push-1` for tiny devices and for all other devices I choose `No reordering`. In this case, it will not work as expected, because it doesn't add any classes for other devices. Where in fact, it should have added `col-sm-push-0` to ensure the `No reordering`, since `col-xs-push-1` was added. The way it is coded now, if someone adds `push-1` for tiny devices, he/she basically has `push-1` for all other devices...

Probably the easiest fix would be to add an option `push-0` and `pull-0`. That way someone can add that to reset the ordering.

**Comment by jrief** [comment]
This is an BS issue, isn't it? If you use ``push-...`` you also have to specify ``pull-...``on another columns.

Or did I miss something, when reading the BS docs?

**Comment by zanderle** [comment]
No, you are right. But having an option of `pull-0` and `push-0` would be nice, don't you think? So that you can reset previous settings. Not really that important though...

**Comment by jrief** [comment]
Oh really? Is there a ``push-0`` / ``pull-0`` in BS3?

**Comment by zanderle** [comment]
Yes. Well, not `push-0`/`pull-0` but there is `pull-xs-0`/`push-xs-0` (and the same for `sm`, `md`, `lg`)
