### ISSUE TITLE
Can't set a 6 / 12 width

### ISSUE THREAD

**Issue by zanderle** [jrief/djangocms-cascade#79]
I want to set default (mobile) width to 6 units and then laptop or tablet width to 12 units. The save happens without any errors, but it changes the 12 units to 6. So I end up getting 6 / 6 instead of 6 / 12 which I chose in the form...

Django 1.6
Cascade 0.5.0

**Comment by zanderle** [comment]
I can see the problem is probably in `BootstrapColumnPlugin` in [container.py lines 271 - 274](https://github.com/jrief/djangocms-cascade/blob/master/cmsplugin_cascade/bootstrap3/container.py#L271).

May I ask why the line 274 is necessary?

**Comment by jrief** [comment]
Unless I misunderstood the concept of BS, does this really make sense?
You normally want larger columns on small devices, and narrower ones on large devices. That's what BS means with "mobile first". Of course I could remove that check, but my intention was to prevent the user from misalignements.

**Comment by zanderle** [comment]
It does make sense. Generally you are correct, but it's not a rule nor a necessity.

As an example, I have a sidebar, which is 3 units wide, but on mobile it's 12 units wide. There are elements inside the sidebar which are stacked when the sidebar is 3 units wide, but should be parallel when the sidebar is 12 units wide... Therefore 6 / 12 width (of the elements inside the sidebar).

But in any case, Bootstrap allows any kind of setup (as long as the width is up to 12), so I guess this plugin should reflect that.

**Comment by zanderle** [comment]
Also 'mobile first' means that the design process should start with mobile and then expand it to other devices. It doesn't imply any kind of design, just that it should start with mobile first (versus desktop first, then thinking about how to implement it on mobile)

**Comment by jrief** [comment]
Can you please try what kind of side-effects you have, if you delete lines 271-273.
Maybe I should add some kind of messaging system to show warnings in situations like these.

BTW, could you please send me your email address.

**Comment by zanderle** [comment]
Couldn't find any side effects to deleting these lines. I tried and everything works perfectly. I created a pull request with this fix.

Personally, I don't think messaging system is necessary. This is all valid Bootstrap structure - I don't think it's this plugin's job to double check if the user is sure they wanted the unusual structure...
