### ISSUE TITLE
Cannot use quotes in accordion panel titles

### ISSUE THREAD

**Issue by Julien-Blanc** [jrief/djangocms-cascade#89]
Quotes are converted to &#39; before serialization to the database (unable to find where exactly), and then are escaped back when displayed.

They should not be escaped in the database.

**Comment by jrief** [comment]
Which plugin, which field?

**Comment by Julien-Blanc** [comment]
Plugin is AccordionPanelPlugin. Field is panel_title.

For the whole story, after a fresh install, filling the title in the interface was not working at all (never serialized to db). Renaming it to panel_title2 made it work (don’t have a clue why, there are no references to panel_title elsewhere in the code, so there must be some dark magic there), with the exception that i had to fix a python 3 compatibility issue (usage of unicode(), line 82 of accordion.py ).

Now, field panel_title2 is serialized to database, but some characters are encoded twice (mainly, single quotes, double quotes, &). Other special characters, such as ’ (apostrophe), are fine.

Note : using python 3.4, djangocms 3.1.2, and djangocms-cascade 0.6.

**Comment by rfleschenberg** [comment]
IIUC, this has been fixed in PR #91? If I am wrong, please re-open :)
