### ISSUE TITLE
Bootstrap3 Buttons plugin in textPlugin

### ISSUE THREAD

**Issue by davidetruffo** [jrief/djangocms-cascade#96]
Hi again,
I'm not able to add the button plugin in the textPlugin, even though the text_enable parameter is set to True for this plugin. Am I missing something?
I'm using ckeditor, here's other specifications:
Python==3.4.3
Django==1.8.4
django-cms==3.1.3
djangocms-cascade==0.6.0
djangocms-text-ckeditor==2.6.0

BTW, this plugin rocks! :+1:

**Comment by jrief** [comment]
No that's vice versa. You can add text as child to the button plugin.
Hmm, but I wondering if this makes sense.

Even if it would be a good idea, I never attempted to add a button inside a CKTextEditorPlugin. Add it into a ColumnPlugin and use styling options.

**Comment by davidetruffo** [comment]
mmm.. it works, but it's not super user friendly, and it produces quite a lot of extra nested markup..
Would you mind if i think about some workaround for that? (if i have time, no promises or high expectations :) )

**Comment by rfleschenberg** [comment]
@davidetruffo Any suggestions / PRs that improve the user experience are welcome. I am closing this issue for now, since it is not really a bug. However, please feel free to make a suggestion.
