### ISSUE TITLE
Translation files update.

### ISSUE THREAD

**Issue by linevich** [jrief/djangocms-cascade#98]
Translation files on [transifex](https://www.transifex.com/jrief/djangocms-cascade/translate/), are outdated. Can you update django.po?

**Comment by jrief** [comment]
Hi Anton,
thanks for the translation. I will merge it next week.
Best Regards, Jacob
Am 30.08.2015 23:55 schrieb "Anton Linevich" <notifications@github.com>:

**Comment by linevich** [comment]
I'm talking about **source translation file**, which was generated by makemessages, not about my translations. This file is outdated, and nearly 50% of project can't be translated.

**Comment by jrief** [comment]
Hi Anton,
Could you please run makemessages, translate that po-file and create a pull
request. I'm currently unable to access the repository, until next week.
Best regards, Jacob
Am 31.08.2015 13:46 schrieb "Anton Linevich" <notifications@github.com>:

**Comment by jrief** [comment]
Now I added the locale files to the project. Thanks for reminding me.
